import json

with open('/home/adminstrator/code/test/language-app/src/data/toeic/grammar.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_grammar = [
  # === Comparative/Superlative ===
  {"id": "tg-61", "pattern": "as...as (Comparison)", "structure": "as + adj/adv + as", "meaning": "So sánh bằng", "example": "The new model is as efficient as the previous one.", "exampleTranslation": "Mẫu mới hiệu quả ngang bằng mẫu trước.", "difficulty": "beginner", "blankedExample": "The new model is _____ efficient _____ the previous one."},
  {"id": "tg-62", "pattern": "Comparative + than", "structure": "adj-er / more adj + than", "meaning": "So sánh hơn", "example": "This quarter's revenue was significantly higher than last quarter's.", "exampleTranslation": "Doanh thu quý này cao hơn đáng kể so với quý trước.", "difficulty": "beginner", "blankedExample": "This quarter's revenue was significantly _____ (high) than last quarter's."},
  {"id": "tg-63", "pattern": "Superlative", "structure": "the + adj-est / most adj", "meaning": "So sánh nhất", "example": "This is the most cost-effective solution available.", "exampleTranslation": "Đây là giải pháp tiết kiệm chi phí nhất hiện có.", "difficulty": "beginner", "blankedExample": "This is _____ (cost-effective) solution available."},
  {"id": "tg-64", "pattern": "the more...the more", "structure": "the + comparative, the + comparative", "meaning": "Càng...càng...", "example": "The more experience you have, the higher the salary.", "exampleTranslation": "Càng có nhiều kinh nghiệm, lương càng cao.", "difficulty": "intermediate", "blankedExample": "_____ more experience you have, _____ higher the salary."},

  # === Causative verbs ===
  {"id": "tg-65", "pattern": "Have something done", "structure": "have + O + V3/ed", "meaning": "Nhờ/thuê ai đó làm gì", "example": "We had the contract reviewed by our legal team.", "exampleTranslation": "Chúng tôi đã nhờ bộ phận pháp lý xem xét hợp đồng.", "difficulty": "intermediate", "blankedExample": "We had the contract _____ (review) by our legal team."},
  {"id": "tg-66", "pattern": "Get something done", "structure": "get + O + V3/ed", "meaning": "Làm cho/nhờ ai đó làm gì", "example": "Please get the report finished before Friday.", "exampleTranslation": "Vui lòng hoàn thành báo cáo trước thứ Sáu.", "difficulty": "intermediate", "blankedExample": "Please get the report _____ (finish) before Friday."},
  {"id": "tg-67", "pattern": "Make/Let/Have + O + V", "structure": "make/let/have + O + V-base", "meaning": "Khiến/cho phép/bảo ai đó làm gì", "example": "The manager let the employees leave early on Friday.", "exampleTranslation": "Quản lý cho phép nhân viên về sớm vào thứ Sáu.", "difficulty": "intermediate", "blankedExample": "The manager let the employees _____ (leave) early on Friday."},

  # === Participle clauses ===
  {"id": "tg-68", "pattern": "Present Participle Clause", "structure": "V-ing..., main clause", "meaning": "Mệnh đề phân từ hiện tại", "example": "Having completed the training, she was promoted to manager.", "exampleTranslation": "Đã hoàn thành khóa đào tạo, cô ấy được thăng chức quản lý.", "difficulty": "advanced", "blankedExample": "_____ (complete) the training, she was promoted to manager."},
  {"id": "tg-69", "pattern": "Past Participle Clause", "structure": "V3/ed..., main clause", "meaning": "Mệnh đề phân từ quá khứ", "example": "Founded in 1990, the company has grown into a global leader.", "exampleTranslation": "Được thành lập năm 1990, công ty đã phát triển thành doanh nghiệp hàng đầu toàn cầu.", "difficulty": "advanced", "blankedExample": "_____ (found) in 1990, the company has grown into a global leader."},

  # === Inversion ===
  {"id": "tg-70", "pattern": "Not only...but also (Inversion)", "structure": "Not only + aux + S + V, but also...", "meaning": "Không chỉ...mà còn (đảo ngữ)", "example": "Not only did the product exceed expectations, but it also won an award.", "exampleTranslation": "Sản phẩm không chỉ vượt kỳ vọng mà còn đoạt giải.", "difficulty": "advanced", "blankedExample": "Not only _____ the product exceed expectations, but it also won an award."},
  {"id": "tg-71", "pattern": "Hardly/Scarcely...when", "structure": "Hardly + had + S + V3 + when...", "meaning": "Vừa mới...thì đã...", "example": "Hardly had the meeting started when the fire alarm went off.", "exampleTranslation": "Cuộc họp vừa mới bắt đầu thì chuông báo cháy kêu.", "difficulty": "advanced", "blankedExample": "Hardly _____ the meeting started when the fire alarm went off."},
  {"id": "tg-72", "pattern": "No sooner...than", "structure": "No sooner + had + S + V3 + than...", "meaning": "Ngay khi...thì...", "example": "No sooner had the CEO announced the merger than stock prices rose.", "exampleTranslation": "Ngay khi CEO công bố sáp nhập, giá cổ phiếu tăng.", "difficulty": "advanced", "blankedExample": "No sooner had the CEO announced the merger _____ stock prices rose."},

  # === Subjunctive ===
  {"id": "tg-73", "pattern": "Subjunctive (suggest/recommend)", "structure": "suggest/recommend + that + S + V-base", "meaning": "Thức giả định (đề nghị/kiến nghị)", "example": "The board recommended that the company invest in new technology.", "exampleTranslation": "Ban giám đốc kiến nghị công ty đầu tư vào công nghệ mới.", "difficulty": "advanced", "blankedExample": "The board recommended that the company _____ (invest) in new technology."},
  {"id": "tg-74", "pattern": "It is important/essential that", "structure": "It is important that + S + V-base", "meaning": "Điều quan trọng là...", "example": "It is essential that every employee attend the safety briefing.", "exampleTranslation": "Điều thiết yếu là mọi nhân viên phải tham dự buổi họp an toàn.", "difficulty": "advanced", "blankedExample": "It is essential that every employee _____ (attend) the safety briefing."},

  # === Word Formation ===
  {"id": "tg-75", "pattern": "Noun → Adjective suffixes", "structure": "-ful, -less, -ous, -ive, -al, -able", "meaning": "Hậu tố chuyển danh từ thành tính từ", "example": "The new policy will be beneficial to all employees.", "exampleTranslation": "Chính sách mới sẽ có lợi cho tất cả nhân viên.", "difficulty": "intermediate", "blankedExample": "The new policy will be _____ (benefit) to all employees."},
  {"id": "tg-76", "pattern": "Verb → Noun suffixes", "structure": "-tion, -ment, -ance, -ence, -al, -ure", "meaning": "Hậu tố chuyển động từ thành danh từ", "example": "The implementation of the new system will take three months.", "exampleTranslation": "Việc triển khai hệ thống mới sẽ mất ba tháng.", "difficulty": "intermediate", "blankedExample": "The _____ (implement) of the new system will take three months."},
  {"id": "tg-77", "pattern": "Adjective → Adverb", "structure": "adj + -ly", "meaning": "Chuyển tính từ thành trạng từ", "example": "The project was completed successfully ahead of the deadline.", "exampleTranslation": "Dự án đã hoàn thành thành công trước thời hạn.", "difficulty": "beginner", "blankedExample": "The project was completed _____ (successful) ahead of the deadline."},
  {"id": "tg-78", "pattern": "Negative prefixes", "structure": "un-, in-, im-, ir-, il-, dis-, non-", "meaning": "Tiền tố phủ định", "example": "The results were inconclusive, so further testing is needed.", "exampleTranslation": "Kết quả không rõ ràng nên cần kiểm tra thêm.", "difficulty": "intermediate", "blankedExample": "The results were _____ (conclusive), so further testing is needed."},

  # === Common TOEIC Structures ===
  {"id": "tg-79", "pattern": "Despite / In spite of", "structure": "Despite / In spite of + N/V-ing", "meaning": "Mặc dù / Bất chấp", "example": "Despite the heavy rain, the event proceeded as planned.", "exampleTranslation": "Mặc dù mưa lớn, sự kiện vẫn diễn ra theo kế hoạch.", "difficulty": "intermediate", "blankedExample": "_____ the heavy rain, the event proceeded as planned."},
  {"id": "tg-80", "pattern": "Although / Even though / Though", "structure": "Although + S + V, S + V", "meaning": "Mặc dù (mệnh đề)", "example": "Although the project was behind schedule, the quality was excellent.", "exampleTranslation": "Mặc dù dự án bị trễ tiến độ, chất lượng vẫn xuất sắc.", "difficulty": "intermediate", "blankedExample": "_____ the project was behind schedule, the quality was excellent."},
  {"id": "tg-81", "pattern": "Whether...or not", "structure": "whether + S + V + or not", "meaning": "Dù...hay không", "example": "Please confirm whether you will attend the meeting or not.", "exampleTranslation": "Vui lòng xác nhận bạn có tham dự cuộc họp hay không.", "difficulty": "intermediate", "blankedExample": "Please confirm _____ you will attend the meeting or not."},
  {"id": "tg-82", "pattern": "So that / In order that", "structure": "S + V + so that + S + can/will + V", "meaning": "Để mà / Nhằm để", "example": "We hired additional staff so that we could meet the deadline.", "exampleTranslation": "Chúng tôi tuyển thêm nhân viên để có thể kịp thời hạn.", "difficulty": "intermediate", "blankedExample": "We hired additional staff _____ we could meet the deadline."},
  {"id": "tg-83", "pattern": "In order to / So as to", "structure": "in order to / so as to + V-base", "meaning": "Để / Nhằm mục đích", "example": "The company invested heavily in order to expand its market share.", "exampleTranslation": "Công ty đầu tư mạnh nhằm mở rộng thị phần.", "difficulty": "intermediate", "blankedExample": "The company invested heavily _____ expand its market share."},

  # === Advanced TOEIC Grammar ===
  {"id": "tg-84", "pattern": "Wish / If only (Regret)", "structure": "wish/if only + S + V2/had V3", "meaning": "Ước gì / Giá mà", "example": "I wish I had accepted the job offer last month.", "exampleTranslation": "Giá mà tôi đã nhận lời mời việc tháng trước.", "difficulty": "advanced", "blankedExample": "I wish I _____ (accept) the job offer last month."},
  {"id": "tg-85", "pattern": "It's time + past tense", "structure": "It's time + S + V2", "meaning": "Đã đến lúc phải...", "example": "It's time the company updated its IT infrastructure.", "exampleTranslation": "Đã đến lúc công ty cập nhật hạ tầng CNTT.", "difficulty": "advanced", "blankedExample": "It's time the company _____ (update) its IT infrastructure."},
  {"id": "tg-86", "pattern": "Cleft sentence (It is...that)", "structure": "It is/was + focus + that + rest", "meaning": "Câu chẻ (nhấn mạnh)", "example": "It was the marketing team that proposed the new campaign.", "exampleTranslation": "Chính đội marketing đã đề xuất chiến dịch mới.", "difficulty": "advanced", "blankedExample": "It was the marketing team _____ proposed the new campaign."},

  # === Connectors & Transitions (Critical for Part 6) ===
  {"id": "tg-87", "pattern": "Furthermore / Moreover / In addition", "structure": "Furthermore/Moreover, + S + V", "meaning": "Hơn nữa / Thêm vào đó", "example": "The product is affordable. Furthermore, it is environmentally friendly.", "exampleTranslation": "Sản phẩm có giá phải chăng. Hơn nữa, nó thân thiện với môi trường.", "difficulty": "intermediate", "blankedExample": "The product is affordable. _____, it is environmentally friendly."},
  {"id": "tg-88", "pattern": "Nevertheless / Nonetheless / However", "structure": "Nevertheless/However, + S + V", "meaning": "Tuy nhiên / Mặc dù vậy", "example": "Sales declined last quarter. Nevertheless, the company remained profitable.", "exampleTranslation": "Doanh số giảm quý trước. Tuy nhiên, công ty vẫn có lãi.", "difficulty": "intermediate", "blankedExample": "Sales declined last quarter. _____, the company remained profitable."},
  {"id": "tg-89", "pattern": "Consequently / Therefore / As a result", "structure": "Therefore/Consequently, + S + V", "meaning": "Do đó / Vì vậy / Kết quả là", "example": "The deadline was extended. Consequently, the team had more time.", "exampleTranslation": "Thời hạn được gia hạn. Do đó, nhóm có thêm thời gian.", "difficulty": "intermediate", "blankedExample": "The deadline was extended. _____, the team had more time."},
  {"id": "tg-90", "pattern": "On the other hand / In contrast", "structure": "On the other hand, + S + V", "meaning": "Mặt khác / Ngược lại", "example": "Online sales increased. On the other hand, in-store sales dropped.", "exampleTranslation": "Doanh số online tăng. Mặt khác, doanh số tại cửa hàng giảm.", "difficulty": "intermediate", "blankedExample": "Online sales increased. _____, in-store sales dropped."},

  # === Collocations (Very common in TOEIC) ===
  {"id": "tg-91", "pattern": "comply with / adhere to", "structure": "comply with / adhere to + N", "meaning": "Tuân thủ / Tuân theo", "example": "All employees must comply with the company's safety regulations.", "exampleTranslation": "Tất cả nhân viên phải tuân thủ quy định an toàn của công ty.", "difficulty": "intermediate", "blankedExample": "All employees must _____ the company's safety regulations."},
  {"id": "tg-92", "pattern": "be subject to", "structure": "be subject to + N", "meaning": "Chịu sự / Phải tuân theo", "example": "All orders are subject to availability.", "exampleTranslation": "Tất cả đơn hàng phụ thuộc vào tình trạng còn hàng.", "difficulty": "advanced", "blankedExample": "All orders are _____ to availability."},
  {"id": "tg-93", "pattern": "in accordance with", "structure": "in accordance with + N", "meaning": "Theo đúng / Phù hợp với", "example": "The refund was processed in accordance with our return policy.", "exampleTranslation": "Hoàn tiền được xử lý theo đúng chính sách trả hàng.", "difficulty": "advanced", "blankedExample": "The refund was processed _____ our return policy."},
  {"id": "tg-94", "pattern": "prior to / following", "structure": "prior to / following + N/V-ing", "meaning": "Trước / Sau", "example": "Please submit the form prior to the deadline.", "exampleTranslation": "Vui lòng nộp mẫu trước thời hạn.", "difficulty": "intermediate", "blankedExample": "Please submit the form _____ the deadline."},
  {"id": "tg-95", "pattern": "be eligible for", "structure": "be eligible for + N", "meaning": "Đủ điều kiện / Có quyền", "example": "Employees who have worked for 5 years are eligible for a bonus.", "exampleTranslation": "Nhân viên làm việc 5 năm đủ điều kiện nhận thưởng.", "difficulty": "intermediate", "blankedExample": "Employees who have worked for 5 years are _____ a bonus."},
  {"id": "tg-96", "pattern": "be attributed to", "structure": "be attributed to + N", "meaning": "Được cho là do / Quy cho", "example": "The company's success is attributed to its innovative products.", "exampleTranslation": "Thành công của công ty được cho là nhờ sản phẩm đổi mới.", "difficulty": "advanced", "blankedExample": "The company's success is _____ its innovative products."},
  {"id": "tg-97", "pattern": "as long as / provided that", "structure": "as long as / provided that + S + V", "meaning": "Miễn là / Với điều kiện là", "example": "You can work remotely as long as you meet the targets.", "exampleTranslation": "Bạn có thể làm việc từ xa miễn là đạt chỉ tiêu.", "difficulty": "intermediate", "blankedExample": "You can work remotely _____ you meet the targets."},
  {"id": "tg-98", "pattern": "regardless of", "structure": "regardless of + N", "meaning": "Bất kể / Không phân biệt", "example": "The policy applies to all staff regardless of their position.", "exampleTranslation": "Chính sách áp dụng cho tất cả nhân viên bất kể chức vụ.", "difficulty": "intermediate", "blankedExample": "The policy applies to all staff _____ their position."},
  {"id": "tg-99", "pattern": "be responsible for", "structure": "be responsible for + N/V-ing", "meaning": "Chịu trách nhiệm về", "example": "The HR department is responsible for processing all applications.", "exampleTranslation": "Phòng nhân sự chịu trách nhiệm xử lý tất cả đơn ứng tuyển.", "difficulty": "intermediate", "blankedExample": "The HR department is _____ processing all applications."},
  {"id": "tg-100", "pattern": "Parallel Structure", "structure": "A, B, and C (same form)", "meaning": "Cấu trúc song song", "example": "The plan includes reducing costs, improving quality, and increasing efficiency.", "exampleTranslation": "Kế hoạch bao gồm giảm chi phí, cải thiện chất lượng và tăng hiệu quả.", "difficulty": "advanced", "blankedExample": "The plan includes reducing costs, improving quality, and _____ (increase) efficiency."}
]

data.extend(new_grammar)
print(f"Total TOEIC grammar points: {len(data)}")

with open('/home/adminstrator/code/test/language-app/src/data/toeic/grammar.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done! Added 40 new TOEIC grammar points.")
