import json

# Generate 500 N2 flashcards - batch 2 (nf-506 to nf-1005)
cards = [
  # === Onomatopoeia (擬音語/擬態語) - 50 cards ===
  {"id":"nf-506","word":"ぐっすり","definition":"ngủ say","example":"昨夜はぐっすり眠れた。","topic":"Onomatopoeia"},
  {"id":"nf-507","word":"ぼんやり","definition":"mơ màng, lơ đễnh","example":"ぼんやりと窓の外を見ていた。","topic":"Onomatopoeia"},
  {"id":"nf-508","word":"すっきり","definition":"sảng khoái, gọn gàng","example":"部屋を片付けたらすっきりした。","topic":"Onomatopoeia"},
  {"id":"nf-509","word":"のんびり","definition":"thong thả, thư thái","example":"休日はのんびり過ごしたい。","topic":"Onomatopoeia"},
  {"id":"nf-510","word":"うっかり","definition":"bất cẩn, sơ ý","example":"うっかり約束を忘れてしまった。","topic":"Onomatopoeia"},
  {"id":"nf-511","word":"がっかり","definition":"thất vọng","example":"試験の結果にがっかりした。","topic":"Onomatopoeia"},
  {"id":"nf-512","word":"ぴったり","definition":"vừa khít, chính xác","example":"このサイズはぴったりだ。","topic":"Onomatopoeia"},
  {"id":"nf-513","word":"そっくり","definition":"giống hệt","example":"彼は父親にそっくりだ。","topic":"Onomatopoeia"},
  {"id":"nf-514","word":"ぐるぐる","definition":"xoay vòng","example":"頭がぐるぐる回っている。","topic":"Onomatopoeia"},
  {"id":"nf-515","word":"きちんと","definition":"ngăn nắp, đàng hoàng","example":"きちんと整理整頓しなさい。","topic":"Onomatopoeia"},
  {"id":"nf-516","word":"どきどき","definition":"hồi hộp, tim đập thình thịch","example":"発表前にどきどきしていた。","topic":"Onomatopoeia"},
  {"id":"nf-517","word":"わくわく","definition":"hào hứng, phấn khích","example":"旅行のことを考えるとわくわくする。","topic":"Onomatopoeia"},
  {"id":"nf-518","word":"いらいら","definition":"bực bội, cáu gắt","example":"渋滞でいらいらした。","topic":"Onomatopoeia"},
  {"id":"nf-519","word":"うろうろ","definition":"đi loanh quanh","example":"道に迷ってうろうろしていた。","topic":"Onomatopoeia"},
  {"id":"nf-520","word":"ばらばら","definition":"rời rạc, tản mát","example":"意見がばらばらでまとまらない。","topic":"Onomatopoeia"},
  {"id":"nf-521","word":"ぶらぶら","definition":"đi dạo, lơ đãng","example":"休みの日は街をぶらぶらする。","topic":"Onomatopoeia"},
  {"id":"nf-522","word":"ぺらぺら","definition":"nói trôi chảy","example":"彼女は英語がぺらぺらだ。","topic":"Onomatopoeia"},
  {"id":"nf-523","word":"こつこつ","definition":"kiên trì, cần mẫn","example":"毎日こつこつ勉強している。","topic":"Onomatopoeia"},
  {"id":"nf-524","word":"しっかり","definition":"chắc chắn, vững vàng","example":"しっかり準備してから出発しよう。","topic":"Onomatopoeia"},
  {"id":"nf-525","word":"ざっと","definition":"sơ qua, đại khái","example":"資料をざっと読んだ。","topic":"Onomatopoeia"},
  {"id":"nf-526","word":"じっと","definition":"yên lặng, chăm chú","example":"彼はじっと黙っていた。","topic":"Onomatopoeia"},
  {"id":"nf-527","word":"そっと","definition":"nhẹ nhàng, lén","example":"赤ちゃんが寝ているので、そっとドアを閉めた。","topic":"Onomatopoeia"},
  {"id":"nf-528","word":"ぎりぎり","definition":"sát nút, vừa vặn","example":"ぎりぎりで電車に間に合った。","topic":"Onomatopoeia"},
  {"id":"nf-529","word":"めちゃくちゃ","definition":"bừa bộn, hỗn loạn","example":"台風で部屋がめちゃくちゃになった。","topic":"Onomatopoeia"},
  {"id":"nf-530","word":"ふわふわ","definition":"mềm mại, bồng bềnh","example":"このパンはふわふわで美味しい。","topic":"Onomatopoeia"},
  {"id":"nf-531","word":"てきぱき","definition":"nhanh nhẹn, gọn gàng","example":"彼女はてきぱきと仕事をこなす。","topic":"Onomatopoeia"},
  {"id":"nf-532","word":"のろのろ","definition":"chậm chạp","example":"のろのろ運転は危険だ。","topic":"Onomatopoeia"},
  {"id":"nf-533","word":"ぺこぺこ","definition":"đói meo; khúm núm","example":"朝から何も食べていないのでお腹がぺこぺこだ。","topic":"Onomatopoeia"},
  {"id":"nf-534","word":"くたくた","definition":"kiệt sức, mệt lả","example":"一日中働いてくたくたになった。","topic":"Onomatopoeia"},
  {"id":"nf-535","word":"にこにこ","definition":"tươi cười","example":"彼女はいつもにこにこしている。","topic":"Onomatopoeia"},
  {"id":"nf-536","word":"ぶつぶつ","definition":"lẩm bẩm, càu nhàu","example":"彼はぶつぶつ文句を言っている。","topic":"Onomatopoeia"},
  {"id":"nf-537","word":"はきはき","definition":"rõ ràng, dứt khoát","example":"面接ではきはきと答えた。","topic":"Onomatopoeia"},
  {"id":"nf-538","word":"こっそり","definition":"lén lút","example":"こっそり部屋を出た。","topic":"Onomatopoeia"},
  {"id":"nf-539","word":"ぼろぼろ","definition":"rách nát, tả tơi","example":"古い本がぼろぼろになった。","topic":"Onomatopoeia"},
  {"id":"nf-540","word":"さっぱり","definition":"sạch sẽ; hoàn toàn không","example":"シャワーを浴びてさっぱりした。","topic":"Onomatopoeia"},
  {"id":"nf-541","word":"しみじみ","definition":"thấm thía, cảm nhận sâu sắc","example":"秋の夕日をしみじみと眺めた。","topic":"Onomatopoeia"},
  {"id":"nf-542","word":"ずるずる","definition":"kéo dài, lê thê","example":"決断をずるずる先延ばしにした。","topic":"Onomatopoeia"},
  {"id":"nf-543","word":"せかせか","definition":"vội vã, hấp tấp","example":"いつもせかせかと動いている。","topic":"Onomatopoeia"},
  {"id":"nf-544","word":"ちゃんと","definition":"đàng hoàng, nghiêm chỉnh","example":"ちゃんと宿題をやりなさい。","topic":"Onomatopoeia"},
  {"id":"nf-545","word":"とことん","definition":"triệt để, tận cùng","example":"とことん話し合おう。","topic":"Onomatopoeia"},
  {"id":"nf-546","word":"なんとなく","definition":"không rõ vì sao, bâng quơ","example":"なんとなく不安な気持ちがする。","topic":"Onomatopoeia"},
  {"id":"nf-547","word":"びっくり","definition":"giật mình, ngạc nhiên","example":"急に名前を呼ばれてびっくりした。","topic":"Onomatopoeia"},
  {"id":"nf-548","word":"ほっと","definition":"thở phào, nhẹ nhõm","example":"無事に着いてほっとした。","topic":"Onomatopoeia"},
  {"id":"nf-549","word":"めきめき","definition":"tiến bộ rõ rệt","example":"日本語の力がめきめき伸びている。","topic":"Onomatopoeia"},
  {"id":"nf-550","word":"よろよろ","definition":"loạng choạng","example":"おじいさんがよろよろと歩いている。","topic":"Onomatopoeia"},
  {"id":"nf-551","word":"ごちゃごちゃ","definition":"bừa bộn, lộn xộn","example":"机の上がごちゃごちゃしている。","topic":"Onomatopoeia"},
  {"id":"nf-552","word":"ぎっしり","definition":"chật ních, đầy ắp","example":"スケジュールがぎっしり詰まっている。","topic":"Onomatopoeia"},
  {"id":"nf-553","word":"がたがた","definition":"rung lắc, lạch cạch","example":"地震で窓ががたがた揺れた。","topic":"Onomatopoeia"},
  {"id":"nf-554","word":"ぞくぞく","definition":"rùng mình (sợ/lạnh/phấn khích)","example":"ホラー映画を見てぞくぞくした。","topic":"Onomatopoeia"},
  {"id":"nf-555","word":"たっぷり","definition":"nhiều, dồi dào","example":"時間はたっぷりあるから急がなくていい。","topic":"Onomatopoeia"},

  # === Business/Keigo - 60 cards ===
  {"id":"nf-556","word":"拝見する (はいけんする)","definition":"xem (kính ngữ khiêm nhường)","example":"資料を拝見しました。","topic":"Business"},
  {"id":"nf-557","word":"申し上げる (もうしあげる)","definition":"nói (kính ngữ khiêm nhường)","example":"一言申し上げます。","topic":"Business"},
  {"id":"nf-558","word":"承知する (しょうちする)","definition":"biết, hiểu (kính ngữ khiêm nhường)","example":"承知いたしました。","topic":"Business"},
  {"id":"nf-559","word":"恐れ入りますが (おそれいりますが)","definition":"xin lỗi phiền nhưng","example":"恐れ入りますが、お名前をお聞かせください。","topic":"Business"},
  {"id":"nf-560","word":"差し支えなければ (さしつかえなければ)","definition":"nếu không phiền","example":"差し支えなければ、ご連絡先を教えてください。","topic":"Business"},
  {"id":"nf-561","word":"検討する (けんとうする)","definition":"xem xét, cân nhắc","example":"提案を検討させていただきます。","topic":"Business"},
  {"id":"nf-562","word":"対応する (たいおうする)","definition":"đối ứng, xử lý","example":"クレームに迅速に対応する。","topic":"Business"},
  {"id":"nf-563","word":"締め切り (しめきり)","definition":"thời hạn, deadline","example":"報告書の締め切りは金曜日です。","topic":"Business"},
  {"id":"nf-564","word":"打ち合わせ (うちあわせ)","definition":"cuộc họp bàn bạc","example":"午後に打ち合わせがあります。","topic":"Business"},
  {"id":"nf-565","word":"手続き (てつづき)","definition":"thủ tục","example":"入社手続きを完了する。","topic":"Business"},
  {"id":"nf-566","word":"取引先 (とりひきさき)","definition":"đối tác kinh doanh","example":"取引先との関係を大切にする。","topic":"Business"},
  {"id":"nf-567","word":"見積もり (みつもり)","definition":"báo giá, ước tính","example":"見積もりを出してください。","topic":"Business"},
  {"id":"nf-568","word":"納品 (のうひん)","definition":"giao hàng","example":"納品は来週の予定です。","topic":"Business"},
  {"id":"nf-569","word":"発注 (はっちゅう)","definition":"đặt hàng","example":"新しい部品を発注した。","topic":"Business"},
  {"id":"nf-570","word":"在庫 (ざいこ)","definition":"hàng tồn kho","example":"在庫を確認してください。","topic":"Business"},
  {"id":"nf-571","word":"売上 (うりあげ)","definition":"doanh số, doanh thu","example":"今月の売上が目標を超えた。","topic":"Business"},
  {"id":"nf-572","word":"経費 (けいひ)","definition":"chi phí, kinh phí","example":"出張の経費を申請する。","topic":"Business"},
  {"id":"nf-573","word":"実績 (じっせき)","definition":"thành tích, kết quả thực tế","example":"営業実績を報告する。","topic":"Business"},
  {"id":"nf-574","word":"方針 (ほうしん)","definition":"phương châm, chính sách","example":"会社の方針に従う。","topic":"Business"},
  {"id":"nf-575","word":"人事 (じんじ)","definition":"nhân sự","example":"人事異動が発表された。","topic":"Business"},
  {"id":"nf-576","word":"総務 (そうむ)","definition":"tổng vụ, hành chính","example":"総務部に問い合わせてください。","topic":"Business"},
  {"id":"nf-577","word":"営業 (えいぎょう)","definition":"kinh doanh, sales","example":"営業部で働いています。","topic":"Business"},
  {"id":"nf-578","word":"企画 (きかく)","definition":"kế hoạch, dự án","example":"新商品の企画を立てる。","topic":"Business"},
  {"id":"nf-579","word":"契約 (けいやく)","definition":"hợp đồng","example":"契約を更新する。","topic":"Business"},
  {"id":"nf-580","word":"交渉 (こうしょう)","definition":"đàm phán","example":"賃金の交渉を行う。","topic":"Business"},
  {"id":"nf-581","word":"提出 (ていしゅつ)","definition":"nộp, đệ trình","example":"書類を提出してください。","topic":"Business"},
  {"id":"nf-582","word":"承認 (しょうにん)","definition":"phê duyệt","example":"上司の承認を得る。","topic":"Business"},
  {"id":"nf-583","word":"効率 (こうりつ)","definition":"hiệu suất","example":"業務の効率を上げる。","topic":"Business"},
  {"id":"nf-584","word":"貢献 (こうけん)","definition":"đóng góp, cống hiến","example":"社会に貢献する。","topic":"Business"},
  {"id":"nf-585","word":"改善 (かいぜん)","definition":"cải thiện","example":"サービスの改善に取り組む。","topic":"Business"},
  {"id":"nf-586","word":"報告 (ほうこく)","definition":"báo cáo","example":"進捗状況を報告する。","topic":"Business"},
  {"id":"nf-587","word":"連携 (れんけい)","definition":"liên kết, phối hợp","example":"部署間の連携を強化する。","topic":"Business"},
  {"id":"nf-588","word":"採用 (さいよう)","definition":"tuyển dụng, áp dụng","example":"新入社員を採用する。","topic":"Business"},
  {"id":"nf-589","word":"退職 (たいしょく)","definition":"nghỉ việc","example":"来月で退職します。","topic":"Business"},
  {"id":"nf-590","word":"昇進 (しょうしん)","definition":"thăng chức","example":"課長に昇進した。","topic":"Business"},
  {"id":"nf-591","word":"異動 (いどう)","definition":"chuyển công tác","example":"大阪支社への異動が決まった。","topic":"Business"},
  {"id":"nf-592","word":"残業 (ざんぎょう)","definition":"làm thêm giờ","example":"今日は残業しなければならない。","topic":"Business"},
  {"id":"nf-593","word":"有給 (ゆうきゅう)","definition":"nghỉ phép có lương","example":"有給を取って旅行に行く。","topic":"Business"},
  {"id":"nf-594","word":"業績 (ぎょうせき)","definition":"thành quả kinh doanh","example":"今期の業績は好調だ。","topic":"Business"},
  {"id":"nf-595","word":"株式 (かぶしき)","definition":"cổ phiếu","example":"株式市場が下落した。","topic":"Business"},
  {"id":"nf-596","word":"融資 (ゆうし)","definition":"cho vay, tài trợ","example":"銀行に融資を申し込む。","topic":"Business"},
  {"id":"nf-597","word":"赤字 (あかじ)","definition":"thua lỗ, thâm hụt","example":"3年連続で赤字が続いている。","topic":"Business"},
  {"id":"nf-598","word":"黒字 (くろじ)","definition":"có lãi","example":"ようやく黒字に転換した。","topic":"Business"},
  {"id":"nf-599","word":"倒産 (とうさん)","definition":"phá sản","example":"不況で多くの企業が倒産した。","topic":"Business"},
  {"id":"nf-600","word":"破産 (はさん)","definition":"vỡ nợ, phá sản (cá nhân)","example":"借金が返せなくて破産した。","topic":"Business"},
  {"id":"nf-601","word":"利益 (りえき)","definition":"lợi nhuận","example":"利益を最大化する。","topic":"Business"},
  {"id":"nf-602","word":"損失 (そんしつ)","definition":"tổn thất","example":"台風による損失は大きかった。","topic":"Business"},
  {"id":"nf-603","word":"予算 (よさん)","definition":"ngân sách","example":"来年度の予算を立てる。","topic":"Business"},
  {"id":"nf-604","word":"税金 (ぜいきん)","definition":"thuế","example":"所得税を納める。","topic":"Business"},
  {"id":"nf-605","word":"消費税 (しょうひぜい)","definition":"thuế tiêu thụ","example":"消費税が10%に上がった。","topic":"Business"},
  {"id":"nf-606","word":"為替 (かわせ)","definition":"tỷ giá hối đoái","example":"為替レートが変動している。","topic":"Business"},
  {"id":"nf-607","word":"輸出 (ゆしゅつ)","definition":"xuất khẩu","example":"自動車の輸出が増加した。","topic":"Business"},
  {"id":"nf-608","word":"輸入 (ゆにゅう)","definition":"nhập khẩu","example":"原材料を海外から輸入する。","topic":"Business"},
  {"id":"nf-609","word":"景気 (けいき)","definition":"kinh tế, tình hình kinh tế","example":"景気が回復しつつある。","topic":"Business"},
  {"id":"nf-610","word":"不況 (ふきょう)","definition":"suy thoái kinh tế","example":"不況の影響で失業率が上がった。","topic":"Business"},
  {"id":"nf-611","word":"競争 (きょうそう)","definition":"cạnh tranh","example":"市場の競争が激しくなっている。","topic":"Business"},
  {"id":"nf-612","word":"戦略 (せんりゃく)","definition":"chiến lược","example":"新しいマーケティング戦略を考える。","topic":"Business"},
  {"id":"nf-613","word":"開発 (かいはつ)","definition":"phát triển, khai phát","example":"新製品の開発に取り組む。","topic":"Business"},
  {"id":"nf-614","word":"製造 (せいぞう)","definition":"sản xuất, chế tạo","example":"この工場で部品を製造している。","topic":"Business"},
  {"id":"nf-615","word":"品質 (ひんしつ)","definition":"chất lượng","example":"品質管理を徹底する。","topic":"Business"},

  # === Social/News - 60 cards ===
  {"id":"nf-616","word":"選挙 (せんきょ)","definition":"bầu cử","example":"来月、総選挙が行われる。","topic":"Social"},
  {"id":"nf-617","word":"政党 (せいとう)","definition":"đảng phái chính trị","example":"新しい政党が結成された。","topic":"Social"},
  {"id":"nf-618","word":"議会 (ぎかい)","definition":"quốc hội, nghị viện","example":"議会で法案が審議されている。","topic":"Social"},
  {"id":"nf-619","word":"法律 (ほうりつ)","definition":"pháp luật","example":"新しい法律が施行された。","topic":"Social"},
  {"id":"nf-620","word":"条約 (じょうやく)","definition":"hiệp ước, điều ước","example":"両国は平和条約を結んだ。","topic":"Social"},
  {"id":"nf-621","word":"外交 (がいこう)","definition":"ngoại giao","example":"外交関係を強化する。","topic":"Social"},
  {"id":"nf-622","word":"犯罪 (はんざい)","definition":"tội phạm","example":"犯罪を防止するための対策。","topic":"Social"},
  {"id":"nf-623","word":"裁判 (さいばん)","definition":"tòa án, phiên tòa","example":"裁判で無罪が証明された。","topic":"Social"},
  {"id":"nf-624","word":"権利 (けんり)","definition":"quyền lợi","example":"市民の権利を守る。","topic":"Social"},
  {"id":"nf-625","word":"義務 (ぎむ)","definition":"nghĩa vụ","example":"納税は国民の義務だ。","topic":"Social"},
  {"id":"nf-626","word":"世論 (せろん・よろん)","definition":"dư luận","example":"世論調査を実施する。","topic":"Social"},
  {"id":"nf-627","word":"報道 (ほうどう)","definition":"đưa tin, báo đạo","example":"マスコミが事件を報道した。","topic":"Social"},
  {"id":"nf-628","word":"災害 (さいがい)","definition":"thiên tai","example":"地震などの災害に備える。","topic":"Social"},
  {"id":"nf-629","word":"被害 (ひがい)","definition":"thiệt hại","example":"台風の被害が広がっている。","topic":"Social"},
  {"id":"nf-630","word":"復興 (ふっこう)","definition":"phục hưng, tái thiết","example":"震災からの復興が進んでいる。","topic":"Social"},
  {"id":"nf-631","word":"避難 (ひなん)","definition":"sơ tán, lánh nạn","example":"避難所に行ってください。","topic":"Social"},
  {"id":"nf-632","word":"支援 (しえん)","definition":"hỗ trợ, viện trợ","example":"被災地に支援物資を送る。","topic":"Social"},
  {"id":"nf-633","word":"福祉 (ふくし)","definition":"phúc lợi","example":"高齢者の福祉サービスを充実させる。","topic":"Social"},
  {"id":"nf-634","word":"少子化 (しょうしか)","definition":"tỷ lệ sinh giảm","example":"少子化が社会問題になっている。","topic":"Social"},
  {"id":"nf-635","word":"高齢化 (こうれいか)","definition":"già hóa dân số","example":"日本は高齢化社会だ。","topic":"Social"},
  {"id":"nf-636","word":"差別 (さべつ)","definition":"phân biệt đối xử","example":"人種差別をなくすべきだ。","topic":"Social"},
  {"id":"nf-637","word":"平等 (びょうどう)","definition":"bình đẳng","example":"男女平等を実現する。","topic":"Social"},
  {"id":"nf-638","word":"汚染 (おせん)","definition":"ô nhiễm","example":"水質汚染が問題になっている。","topic":"Social"},
  {"id":"nf-639","word":"温暖化 (おんだんか)","definition":"sự ấm lên toàn cầu","example":"地球温暖化を防ぐ努力が必要だ。","topic":"Social"},
  {"id":"nf-640","word":"資源 (しげん)","definition":"tài nguyên","example":"天然資源を大切にする。","topic":"Social"},
  {"id":"nf-641","word":"再生 (さいせい)","definition":"tái sinh, tái tạo","example":"資源の再生利用を推進する。","topic":"Social"},
  {"id":"nf-642","word":"エネルギー","definition":"năng lượng","example":"再生可能エネルギーの利用が増えている。","topic":"Social"},
  {"id":"nf-643","word":"人口 (じんこう)","definition":"dân số","example":"都市の人口が増加している。","topic":"Social"},
  {"id":"nf-644","word":"移民 (いみん)","definition":"di dân","example":"移民政策について議論する。","topic":"Social"},
  {"id":"nf-645","word":"難民 (なんみん)","definition":"người tị nạn","example":"難民を受け入れる。","topic":"Social"},
  {"id":"nf-646","word":"国際 (こくさい)","definition":"quốc tế","example":"国際会議に出席する。","topic":"Social"},
  {"id":"nf-647","word":"貿易 (ぼうえき)","definition":"thương mại","example":"自由貿易協定を結ぶ。","topic":"Social"},
  {"id":"nf-648","word":"格差 (かくさ)","definition":"chênh lệch, khoảng cách","example":"経済格差が広がっている。","topic":"Social"},
  {"id":"nf-649","word":"雇用 (こよう)","definition":"tuyển dụng, việc làm","example":"雇用を創出する政策。","topic":"Social"},
  {"id":"nf-650","word":"失業 (しつぎょう)","definition":"thất nghiệp","example":"失業率が上昇している。","topic":"Social"},
  {"id":"nf-651","word":"賃金 (ちんぎん)","definition":"tiền lương, tiền công","example":"最低賃金が引き上げられた。","topic":"Social"},
  {"id":"nf-652","word":"年金 (ねんきん)","definition":"lương hưu, trợ cấp","example":"年金制度を改革する。","topic":"Social"},
  {"id":"nf-653","word":"保険 (ほけん)","definition":"bảo hiểm","example":"健康保険に加入する。","topic":"Social"},
  {"id":"nf-654","word":"治安 (ちあん)","definition":"an ninh trật tự","example":"この地域は治安がいい。","topic":"Social"},
  {"id":"nf-655","word":"防災 (ぼうさい)","definition":"phòng chống thiên tai","example":"防災訓練を行う。","topic":"Social"},
  {"id":"nf-656","word":"規制 (きせい)","definition":"quy chế, hạn chế","example":"環境に関する規制が厳しくなった。","topic":"Social"},
  {"id":"nf-657","word":"自治体 (じちたい)","definition":"chính quyền địa phương","example":"自治体が補助金を出す。","topic":"Social"},
  {"id":"nf-658","word":"公共 (こうきょう)","definition":"công cộng","example":"公共交通機関を利用する。","topic":"Social"},
  {"id":"nf-659","word":"予防 (よぼう)","definition":"phòng ngừa","example":"病気の予防に努める。","topic":"Social"},
  {"id":"nf-660","word":"対策 (たいさく)","definition":"biện pháp đối phó","example":"地震対策を強化する。","topic":"Social"},
  {"id":"nf-661","word":"制度 (せいど)","definition":"chế độ, hệ thống","example":"教育制度を改革する。","topic":"Social"},
  {"id":"nf-662","word":"方針 (ほうしん)","definition":"phương châm, chủ trương","example":"政府の新しい方針が発表された。","topic":"Social"},
  {"id":"nf-663","word":"課題 (かだい)","definition":"vấn đề cần giải quyết","example":"少子化は日本の大きな課題だ。","topic":"Social"},
  {"id":"nf-664","word":"問題意識 (もんだいいしき)","definition":"ý thức về vấn đề","example":"環境に対する問題意識が高まっている。","topic":"Social"},
  {"id":"nf-665","word":"取り組み (とりくみ)","definition":"nỗ lực, sáng kiến","example":"環境保護への取り組みが評価された。","topic":"Social"},
  {"id":"nf-666","word":"普及 (ふきゅう)","definition":"phổ cập, phổ biến","example":"スマートフォンが急速に普及した。","topic":"Social"},
  {"id":"nf-667","word":"促進 (そくしん)","definition":"thúc đẩy, xúc tiến","example":"観光の促進に力を入れている。","topic":"Social"},
  {"id":"nf-668","word":"削減 (さくげん)","definition":"cắt giảm","example":"CO2排出量を削減する。","topic":"Social"},
  {"id":"nf-669","word":"拡大 (かくだい)","definition":"mở rộng","example":"事業を海外に拡大する。","topic":"Social"},
  {"id":"nf-670","word":"縮小 (しゅくしょう)","definition":"thu nhỏ, thu hẹp","example":"市場が縮小している。","topic":"Social"},
  {"id":"nf-671","word":"維持 (いじ)","definition":"duy trì","example":"健康を維持するために運動する。","topic":"Social"},
  {"id":"nf-672","word":"確保 (かくほ)","definition":"đảm bảo, xác bảo","example":"安全を確保する。","topic":"Social"},
  {"id":"nf-673","word":"把握 (はあく)","definition":"nắm bắt, hiểu rõ","example":"状況を正確に把握する。","topic":"Social"},
  {"id":"nf-674","word":"判断 (はんだん)","definition":"phán đoán, quyết định","example":"正しい判断を下す。","topic":"Social"},
  {"id":"nf-675","word":"指摘 (してき)","definition":"chỉ ra, chỉ trích","example":"問題点を指摘する。","topic":"Social"},

  # === Compound Verbs - 80 cards ===
  {"id":"nf-676","word":"打ち合わせる (うちあわせる)","definition":"bàn bạc, thương lượng","example":"プロジェクトについて打ち合わせる。","topic":"Compound Verbs"},
  {"id":"nf-677","word":"取り組む (とりくむ)","definition":"nỗ lực, dấn thân","example":"環境問題に取り組む。","topic":"Compound Verbs"},
  {"id":"nf-678","word":"見直す (みなおす)","definition":"xem xét lại, đánh giá lại","example":"計画を見直す必要がある。","topic":"Compound Verbs"},
  {"id":"nf-679","word":"思い切る (おもいきる)","definition":"quyết tâm, dứt khoát","example":"思い切って会社を辞めた。","topic":"Compound Verbs"},
  {"id":"nf-680","word":"取り消す (とりけす)","definition":"hủy bỏ, thu hồi","example":"予約を取り消した。","topic":"Compound Verbs"},
  {"id":"nf-681","word":"立ち上がる (たちあがる)","definition":"đứng dậy, khởi động","example":"困難から立ち上がった。","topic":"Compound Verbs"},
  {"id":"nf-682","word":"引き受ける (ひきうける)","definition":"nhận lãnh, đảm nhận","example":"大きなプロジェクトを引き受けた。","topic":"Compound Verbs"},
  {"id":"nf-683","word":"切り替える (きりかえる)","definition":"chuyển đổi","example":"気持ちを切り替えて頑張る。","topic":"Compound Verbs"},
  {"id":"nf-684","word":"追いつく (おいつく)","definition":"đuổi kịp","example":"先頭に追いつくことができた。","topic":"Compound Verbs"},
  {"id":"nf-685","word":"落ち着く (おちつく)","definition":"bình tĩnh, ổn định","example":"まず落ち着いて考えよう。","topic":"Compound Verbs"},
  {"id":"nf-686","word":"申し込む (もうしこむ)","definition":"đăng ký, nộp đơn","example":"大会に参加を申し込んだ。","topic":"Compound Verbs"},
  {"id":"nf-687","word":"問い合わせる (といあわせる)","definition":"hỏi thăm, liên hệ","example":"詳細について問い合わせた。","topic":"Compound Verbs"},
  {"id":"nf-688","word":"繰り返す (くりかえす)","definition":"lặp lại","example":"同じミスを繰り返さないようにする。","topic":"Compound Verbs"},
  {"id":"nf-689","word":"振り返る (ふりかえる)","definition":"nhìn lại, hồi tưởng","example":"過去を振り返ってみる。","topic":"Compound Verbs"},
  {"id":"nf-690","word":"見つかる (みつかる)","definition":"được tìm thấy","example":"なくした財布が見つかった。","topic":"Compound Verbs"},
  {"id":"nf-691","word":"持ち上げる (もちあげる)","definition":"nhấc lên, nâng lên","example":"重い荷物を持ち上げた。","topic":"Compound Verbs"},
  {"id":"nf-692","word":"飛び出す (とびだす)","definition":"nhảy ra, lao ra","example":"子供が急に道に飛び出した。","topic":"Compound Verbs"},
  {"id":"nf-693","word":"差し出す (さしだす)","definition":"đưa ra, dâng","example":"名刺を差し出した。","topic":"Compound Verbs"},
  {"id":"nf-694","word":"突き当たる (つきあたる)","definition":"đụng phải, gặp phải","example":"道の突き当たりを右に曲がる。","topic":"Compound Verbs"},
  {"id":"nf-695","word":"踏み切る (ふみきる)","definition":"quyết định, dứt khoát","example":"転職に踏み切った。","topic":"Compound Verbs"},
  {"id":"nf-696","word":"締め切る (しめきる)","definition":"đóng hạn, kết thúc","example":"応募を締め切った。","topic":"Compound Verbs"},
  {"id":"nf-697","word":"思いつく (おもいつく)","definition":"nghĩ ra, nảy ra ý tưởng","example":"いいアイデアを思いついた。","topic":"Compound Verbs"},
  {"id":"nf-698","word":"気づく (きづく)","definition":"nhận ra, phát hiện","example":"間違いに気づいた。","topic":"Compound Verbs"},
  {"id":"nf-699","word":"片付ける (かたづける)","definition":"dọn dẹp, giải quyết","example":"部屋を片付けなさい。","topic":"Compound Verbs"},
  {"id":"nf-700","word":"組み立てる (くみたてる)","definition":"lắp ráp","example":"家具を組み立てる。","topic":"Compound Verbs"},
  {"id":"nf-701","word":"受け取る (うけとる)","definition":"nhận, tiếp nhận","example":"荷物を受け取った。","topic":"Compound Verbs"},
  {"id":"nf-702","word":"受け入れる (うけいれる)","definition":"chấp nhận, tiếp nhận","example":"留学生を受け入れる。","topic":"Compound Verbs"},
  {"id":"nf-703","word":"乗り換える (のりかえる)","definition":"đổi tàu/xe","example":"東京駅で乗り換えてください。","topic":"Compound Verbs"},
  {"id":"nf-704","word":"乗り越える (のりこえる)","definition":"vượt qua","example":"困難を乗り越える。","topic":"Compound Verbs"},
  {"id":"nf-705","word":"話し合う (はなしあう)","definition":"bàn bạc, thảo luận","example":"問題について話し合った。","topic":"Compound Verbs"},
  {"id":"nf-706","word":"向き合う (むきあう)","definition":"đối mặt","example":"現実と向き合うべきだ。","topic":"Compound Verbs"},
  {"id":"nf-707","word":"付き合う (つきあう)","definition":"giao du, hẹn hò","example":"3年間付き合っている。","topic":"Compound Verbs"},
  {"id":"nf-708","word":"取り上げる (とりあげる)","definition":"đề cập, lấy lên","example":"メディアがこの問題を取り上げた。","topic":"Compound Verbs"},
  {"id":"nf-709","word":"売り切れる (うりきれる)","definition":"bán hết, cháy hàng","example":"チケットがすぐに売り切れた。","topic":"Compound Verbs"},
  {"id":"nf-710","word":"追い込む (おいこむ)","definition":"dồn ép, bức ép","example":"試験前に追い込みをかける。","topic":"Compound Verbs"},
  {"id":"nf-711","word":"吹き飛ばす (ふきとばす)","definition":"thổi bay","example":"強風で看板が吹き飛ばされた。","topic":"Compound Verbs"},
  {"id":"nf-712","word":"巻き込む (まきこむ)","definition":"cuốn vào, lôi kéo","example":"事件に巻き込まれた。","topic":"Compound Verbs"},
  {"id":"nf-713","word":"見守る (みまもる)","definition":"theo dõi, trông chừng","example":"子供の成長を見守る。","topic":"Compound Verbs"},
  {"id":"nf-714","word":"生み出す (うみだす)","definition":"tạo ra, sinh ra","example":"新しい価値を生み出す。","topic":"Compound Verbs"},
  {"id":"nf-715","word":"使い果たす (つかいはたす)","definition":"dùng hết, tiêu hết","example":"予算を使い果たした。","topic":"Compound Verbs"},
  {"id":"nf-716","word":"当てはまる (あてはまる)","definition":"phù hợp, đúng","example":"この条件に当てはまる人。","topic":"Compound Verbs"},
  {"id":"nf-717","word":"割り込む (わりこむ)","definition":"chen ngang, xen vào","example":"列に割り込まないでください。","topic":"Compound Verbs"},
  {"id":"nf-718","word":"立ち寄る (たちよる)","definition":"ghé qua","example":"帰りにスーパーに立ち寄った。","topic":"Compound Verbs"},
  {"id":"nf-719","word":"呼びかける (よびかける)","definition":"kêu gọi","example":"市民に協力を呼びかけた。","topic":"Compound Verbs"},
  {"id":"nf-720","word":"見落とす (みおとす)","definition":"bỏ sót, không nhận ra","example":"重要なポイントを見落とした。","topic":"Compound Verbs"},
  {"id":"nf-721","word":"取り戻す (とりもどす)","definition":"lấy lại, khôi phục","example":"自信を取り戻した。","topic":"Compound Verbs"},
  {"id":"nf-722","word":"追い越す (おいこす)","definition":"vượt qua","example":"前の車を追い越した。","topic":"Compound Verbs"},
  {"id":"nf-723","word":"引き起こす (ひきおこす)","definition":"gây ra","example":"不注意が事故を引き起こした。","topic":"Compound Verbs"},
  {"id":"nf-724","word":"見つめる (みつめる)","definition":"nhìn chằm chằm","example":"彼女をじっと見つめた。","topic":"Compound Verbs"},
  {"id":"nf-725","word":"差し支える (さしつかえる)","definition":"gây trở ngại","example":"仕事に差し支えることはありません。","topic":"Compound Verbs"},
  {"id":"nf-726","word":"やり直す (やりなおす)","definition":"làm lại","example":"最初からやり直す。","topic":"Compound Verbs"},
  {"id":"nf-727","word":"通り過ぎる (とおりすぎる)","definition":"đi qua, lướt qua","example":"駅を通り過ぎてしまった。","topic":"Compound Verbs"},
  {"id":"nf-728","word":"積み重ねる (つみかさねる)","definition":"tích lũy, chồng chất","example":"経験を積み重ねてきた。","topic":"Compound Verbs"},
  {"id":"nf-729","word":"呼び出す (よびだす)","definition":"gọi ra, triệu tập","example":"上司に呼び出された。","topic":"Compound Verbs"},
  {"id":"nf-730","word":"飛び込む (とびこむ)","definition":"nhảy vào, lao vào","example":"プールに飛び込んだ。","topic":"Compound Verbs"},
  {"id":"nf-731","word":"吸い込む (すいこむ)","definition":"hít vào, hút vào","example":"新鮮な空気を吸い込んだ。","topic":"Compound Verbs"},
  {"id":"nf-732","word":"突き進む (つきすすむ)","definition":"tiến thẳng, xông pha","example":"目標に向かって突き進む。","topic":"Compound Verbs"},
  {"id":"nf-733","word":"振り向く (ふりむく)","definition":"quay lại nhìn","example":"名前を呼ばれて振り向いた。","topic":"Compound Verbs"},
  {"id":"nf-734","word":"思い出す (おもいだす)","definition":"nhớ ra, hồi tưởng","example":"昔のことを思い出した。","topic":"Compound Verbs"},
  {"id":"nf-735","word":"話しかける (はなしかける)","definition":"bắt chuyện","example":"知らない人に話しかけた。","topic":"Compound Verbs"},
  {"id":"nf-736","word":"投げ出す (なげだす)","definition":"bỏ cuộc, quăng ra","example":"途中で投げ出してはいけない。","topic":"Compound Verbs"},
  {"id":"nf-737","word":"掘り下げる (ほりさげる)","definition":"đào sâu, tìm hiểu kỹ","example":"テーマを掘り下げて研究する。","topic":"Compound Verbs"},
  {"id":"nf-738","word":"使いこなす (つかいこなす)","definition":"sử dụng thành thạo","example":"新しいソフトを使いこなす。","topic":"Compound Verbs"},
  {"id":"nf-739","word":"間に合う (まにあう)","definition":"kịp giờ","example":"ぎりぎり電車に間に合った。","topic":"Compound Verbs"},
  {"id":"nf-740","word":"見込む (みこむ)","definition":"dự kiến, kỳ vọng","example":"売上の増加を見込んでいる。","topic":"Compound Verbs"},
  {"id":"nf-741","word":"引き出す (ひきだす)","definition":"rút ra, khai thác","example":"能力を最大限に引き出す。","topic":"Compound Verbs"},
  {"id":"nf-742","word":"落ち込む (おちこむ)","definition":"suy sụp, giảm sút","example":"失敗して落ち込んでいる。","topic":"Compound Verbs"},
  {"id":"nf-743","word":"取り除く (とりのぞく)","definition":"loại bỏ","example":"不安を取り除く。","topic":"Compound Verbs"},
  {"id":"nf-744","word":"盛り上がる (もりあがる)","definition":"sôi nổi, hứng khởi","example":"パーティーが盛り上がった。","topic":"Compound Verbs"},
  {"id":"nf-745","word":"切り開く (きりひらく)","definition":"khai phá, mở ra","example":"新しい分野を切り開く。","topic":"Compound Verbs"},
  {"id":"nf-746","word":"見渡す (みわたす)","definition":"nhìn khắp, phóng tầm mắt","example":"山の上から街を見渡した。","topic":"Compound Verbs"},
  {"id":"nf-747","word":"押し付ける (おしつける)","definition":"ép buộc, đẩy cho","example":"仕事を他人に押し付ける。","topic":"Compound Verbs"},
  {"id":"nf-748","word":"立ち上げる (たちあげる)","definition":"khởi động, thành lập","example":"新しいプロジェクトを立ち上げた。","topic":"Compound Verbs"},
  {"id":"nf-749","word":"打ち切る (うちきる)","definition":"cắt đứt, chấm dứt","example":"支援を打ち切る。","topic":"Compound Verbs"},
  {"id":"nf-750","word":"突き止める (つきとめる)","definition":"tìm ra, xác định","example":"原因を突き止めた。","topic":"Compound Verbs"},
  {"id":"nf-751","word":"食い止める (くいとめる)","definition":"ngăn chặn","example":"被害の拡大を食い止める。","topic":"Compound Verbs"},
  {"id":"nf-752","word":"見極める (みきわめる)","definition":"nhận rõ, đánh giá chính xác","example":"状況を見極めてから判断する。","topic":"Compound Verbs"},
  {"id":"nf-753","word":"思い込む (おもいこむ)","definition":"tin chắc (sai lầm)","example":"自分が正しいと思い込んでいた。","topic":"Compound Verbs"},
  {"id":"nf-754","word":"吹き出す (ふきだす)","definition":"bật cười; phun ra","example":"おかしくて吹き出してしまった。","topic":"Compound Verbs"},
  {"id":"nf-755","word":"溶け込む (とけこむ)","definition":"hòa nhập","example":"地域社会に溶け込む。","topic":"Compound Verbs"},

  # === N2 Adjectives - 60 cards ===
  {"id":"nf-756","word":"著しい (いちじるしい)","definition":"đáng kể, rõ rệt","example":"技術の著しい進歩が見られる。","topic":"Adjectives"},
  {"id":"nf-757","word":"著名 (ちょめい)","definition":"nổi tiếng, trứ danh","example":"著名な科学者の講演を聞いた。","topic":"Adjectives"},
  {"id":"nf-758","word":"顕著 (けんちょ)","definition":"nổi bật, rõ ràng","example":"環境問題の影響が顕著になっている。","topic":"Adjectives"},
  {"id":"nf-759","word":"膨大 (ぼうだい)","definition":"khổng lồ, đồ sộ","example":"膨大なデータを処理する。","topic":"Adjectives"},
  {"id":"nf-760","word":"莫大 (ばくだい)","definition":"rất lớn, khổng lồ (tiền)","example":"莫大な費用がかかった。","topic":"Adjectives"},
  {"id":"nf-761","word":"微妙 (びみょう)","definition":"tế nhị, tinh tế","example":"微妙な問題なので慎重に対応する。","topic":"Adjectives"},
  {"id":"nf-762","word":"曖昧 (あいまい)","definition":"mơ hồ, không rõ ràng","example":"曖昧な表現は避けるべきだ。","topic":"Adjectives"},
  {"id":"nf-763","word":"明確 (めいかく)","definition":"rõ ràng, minh bạch","example":"目標を明確にする。","topic":"Adjectives"},
  {"id":"nf-764","word":"適切 (てきせつ)","definition":"phù hợp, thích hợp","example":"適切な対応をとる。","topic":"Adjectives"},
  {"id":"nf-765","word":"妥当 (だとう)","definition":"thỏa đáng, hợp lý","example":"妥当な判断だと思う。","topic":"Adjectives"},
  {"id":"nf-766","word":"深刻 (しんこく)","definition":"nghiêm trọng","example":"人手不足が深刻な問題だ。","topic":"Adjectives"},
  {"id":"nf-767","word":"慎重 (しんちょう)","definition":"thận trọng, cẩn thận","example":"慎重に検討する必要がある。","topic":"Adjectives"},
  {"id":"nf-768","word":"大胆 (だいたん)","definition":"táo bạo, mạnh dạn","example":"大胆な改革を行う。","topic":"Adjectives"},
  {"id":"nf-769","word":"些細 (ささい)","definition":"nhỏ nhặt, vụn vặt","example":"些細なことで怒らないでください。","topic":"Adjectives"},
  {"id":"nf-770","word":"重大 (じゅうだい)","definition":"trọng đại, nghiêm trọng","example":"重大な決断を下す。","topic":"Adjectives"},
  {"id":"nf-771","word":"有益 (ゆうえき)","definition":"hữu ích, có lợi","example":"有益な情報を提供する。","topic":"Adjectives"},
  {"id":"nf-772","word":"有害 (ゆうがい)","definition":"có hại","example":"有害な物質を含む。","topic":"Adjectives"},
  {"id":"nf-773","word":"豊富 (ほうふ)","definition":"phong phú, dồi dào","example":"経験が豊富な人材を求めている。","topic":"Adjectives"},
  {"id":"nf-774","word":"貴重 (きちょう)","definition":"quý giá, quý báu","example":"貴重な経験をさせていただいた。","topic":"Adjectives"},
  {"id":"nf-775","word":"厳格 (げんかく)","definition":"nghiêm khắc, nghiêm ngặt","example":"厳格な規則に従う。","topic":"Adjectives"},
  {"id":"nf-776","word":"寛大 (かんだい)","definition":"khoan dung, rộng lượng","example":"寛大な処置を求める。","topic":"Adjectives"},
  {"id":"nf-777","word":"柔軟 (じゅうなん)","definition":"linh hoạt, mềm dẻo","example":"柔軟な対応が求められる。","topic":"Adjectives"},
  {"id":"nf-778","word":"頑丈 (がんじょう)","definition":"vững chắc, chắc chắn","example":"頑丈な建物が地震に耐えた。","topic":"Adjectives"},
  {"id":"nf-779","word":"急速 (きゅうそく)","definition":"nhanh chóng","example":"技術が急速に発展している。","topic":"Adjectives"},
  {"id":"nf-780","word":"穏やか (おだやか)","definition":"yên bình, ôn hòa","example":"穏やかな天気が続いている。","topic":"Adjectives"},
  {"id":"nf-781","word":"激しい (はげしい)","definition":"dữ dội, kịch liệt","example":"激しい雨が降っている。","topic":"Adjectives"},
  {"id":"nf-782","word":"鈍い (にぶい)","definition":"chậm chạp, đần độn","example":"反応が鈍い。","topic":"Adjectives"},
  {"id":"nf-783","word":"鋭い (するどい)","definition":"sắc bén, nhạy bén","example":"鋭い分析力を持っている。","topic":"Adjectives"},
  {"id":"nf-784","word":"密接 (みっせつ)","definition":"mật thiết, chặt chẽ","example":"経済と環境は密接に関係している。","topic":"Adjectives"},
  {"id":"nf-785","word":"独自 (どくじ)","definition":"riêng biệt, độc đáo","example":"独自の技術を開発した。","topic":"Adjectives"},
  {"id":"nf-786","word":"多彩 (たさい)","definition":"đa dạng, phong phú","example":"多彩なメニューが揃っている。","topic":"Adjectives"},
  {"id":"nf-787","word":"顕著 (けんちょ)","definition":"nổi bật, rõ ràng","example":"経済成長が顕著だ。","topic":"Adjectives"},
  {"id":"nf-788","word":"不可欠 (ふかけつ)","definition":"không thể thiếu","example":"チームワークは不可欠だ。","topic":"Adjectives"},
  {"id":"nf-789","word":"円滑 (えんかつ)","definition":"trôi chảy, suôn sẻ","example":"会議を円滑に進める。","topic":"Adjectives"},
  {"id":"nf-790","word":"迅速 (じんそく)","definition":"nhanh chóng, mau lẹ","example":"迅速に対応してください。","topic":"Adjectives"},
  {"id":"nf-791","word":"多大 (ただい)","definition":"rất nhiều, to lớn","example":"多大な迷惑をかけた。","topic":"Adjectives"},
  {"id":"nf-792","word":"過剰 (かじょう)","definition":"quá mức, thừa thãi","example":"過剰な包装は環境に悪い。","topic":"Adjectives"},
  {"id":"nf-793","word":"不十分 (ふじゅうぶん)","definition":"không đầy đủ, thiếu","example":"準備が不十分だった。","topic":"Adjectives"},
  {"id":"nf-794","word":"頻繁 (ひんぱん)","definition":"thường xuyên, liên tục","example":"最近地震が頻繁に起きている。","topic":"Adjectives"},
  {"id":"nf-795","word":"漠然 (ばくぜん)","definition":"mơ hồ, mông lung","example":"将来に対して漠然とした不安がある。","topic":"Adjectives"},
  {"id":"nf-796","word":"健全 (けんぜん)","definition":"lành mạnh, khỏe mạnh","example":"健全な精神は健全な身体に宿る。","topic":"Adjectives"},
  {"id":"nf-797","word":"対等 (たいとう)","definition":"ngang hàng, bình đẳng","example":"対等な立場で話し合う。","topic":"Adjectives"},
  {"id":"nf-798","word":"僅か (わずか)","definition":"chỉ một chút, ít ỏi","example":"僅かな差で負けた。","topic":"Adjectives"},
  {"id":"nf-799","word":"純粋 (じゅんすい)","definition":"thuần khiết, trong sáng","example":"純粋な気持ちで取り組む。","topic":"Adjectives"},
  {"id":"nf-800","word":"素朴 (そぼく)","definition":"mộc mạc, đơn giản","example":"素朴な疑問がある。","topic":"Adjectives"},
  {"id":"nf-801","word":"巧み (たくみ)","definition":"khéo léo, điêu luyện","example":"巧みな話術で聴衆を魅了した。","topic":"Adjectives"},
  {"id":"nf-802","word":"余分 (よぶん)","definition":"thừa, dư","example":"余分なものを持って行かない。","topic":"Adjectives"},
  {"id":"nf-803","word":"相互 (そうご)","definition":"lẫn nhau, tương hỗ","example":"相互理解を深める。","topic":"Adjectives"},
  {"id":"nf-804","word":"一致 (いっち)","definition":"nhất trí, phù hợp","example":"意見が一致した。","topic":"Adjectives"},
  {"id":"nf-805","word":"矛盾 (むじゅん)","definition":"mâu thuẫn","example":"彼の発言には矛盾がある。","topic":"Adjectives"},
  {"id":"nf-806","word":"抽象的 (ちゅうしょうてき)","definition":"trừu tượng","example":"抽象的な表現が多い。","topic":"Adjectives"},
  {"id":"nf-807","word":"具体的 (ぐたいてき)","definition":"cụ thể","example":"具体的な計画を立てる。","topic":"Adjectives"},
  {"id":"nf-808","word":"物足りない (ものたりない)","definition":"không đủ, chưa thỏa mãn","example":"量が少なくて物足りない。","topic":"Adjectives"},
  {"id":"nf-809","word":"見苦しい (みぐるしい)","definition":"xấu xí, khó coi","example":"見苦しい行動は慎みなさい。","topic":"Adjectives"},
  {"id":"nf-810","word":"情けない (なさけない)","definition":"đáng thất vọng, thảm hại","example":"こんな簡単な問題も解けないなんて情けない。","topic":"Adjectives"},
  {"id":"nf-811","word":"図々しい (ずうずうしい)","definition":"trơ trẽn, dày mặt","example":"そんな図々しいことは言えない。","topic":"Adjectives"},
  {"id":"nf-812","word":"空しい (むなしい)","definition":"hư vô, trống rỗng","example":"努力が空しく終わった。","topic":"Adjectives"},
  {"id":"nf-813","word":"潔い (いさぎよい)","definition":"dứt khoát, sòng phẳng","example":"潔く負けを認めた。","topic":"Adjectives"},
  {"id":"nf-814","word":"心強い (こころづよい)","definition":"vững tâm, yên lòng","example":"あなたがいてくれて心強い。","topic":"Adjectives"},
  {"id":"nf-815","word":"煩わしい (わずらわしい)","definition":"phiền phức, rắc rối","example":"煩わしい手続きを省略する。","topic":"Adjectives"},

  # === Abstract Nouns - 60 cards ===
  {"id":"nf-816","word":"影響 (えいきょう)","definition":"ảnh hưởng","example":"環境に悪い影響を与える。","topic":"Abstract Nouns"},
  {"id":"nf-817","word":"傾向 (けいこう)","definition":"xu hướng","example":"若者の間で健康志向の傾向がある。","topic":"Abstract Nouns"},
  {"id":"nf-818","word":"現象 (げんしょう)","definition":"hiện tượng","example":"地球温暖化という現象が起きている。","topic":"Abstract Nouns"},
  {"id":"nf-819","word":"要因 (よういん)","definition":"nguyên nhân, yếu tố","example":"成功の要因を分析する。","topic":"Abstract Nouns"},
  {"id":"nf-820","word":"背景 (はいけい)","definition":"bối cảnh, nền tảng","example":"事件の背景を調べる。","topic":"Abstract Nouns"},
  {"id":"nf-821","word":"根拠 (こんきょ)","definition":"căn cứ, cơ sở","example":"科学的な根拠に基づく。","topic":"Abstract Nouns"},
  {"id":"nf-822","word":"前提 (ぜんてい)","definition":"tiền đề","example":"この議論の前提を確認しよう。","topic":"Abstract Nouns"},
  {"id":"nf-823","word":"本質 (ほんしつ)","definition":"bản chất","example":"問題の本質を見極める。","topic":"Abstract Nouns"},
  {"id":"nf-824","word":"側面 (そくめん)","definition":"khía cạnh, mặt","example":"問題の別の側面も考える。","topic":"Abstract Nouns"},
  {"id":"nf-825","word":"観点 (かんてん)","definition":"quan điểm, góc nhìn","example":"異なる観点から分析する。","topic":"Abstract Nouns"},
  {"id":"nf-826","word":"対象 (たいしょう)","definition":"đối tượng","example":"調査の対象は大学生だ。","topic":"Abstract Nouns"},
  {"id":"nf-827","word":"範囲 (はんい)","definition":"phạm vi","example":"調査の範囲を広げる。","topic":"Abstract Nouns"},
  {"id":"nf-828","word":"段階 (だんかい)","definition":"giai đoạn","example":"計画は最終段階に入った。","topic":"Abstract Nouns"},
  {"id":"nf-829","word":"過程 (かてい)","definition":"quá trình","example":"成長の過程で多くを学んだ。","topic":"Abstract Nouns"},
  {"id":"nf-830","word":"経緯 (けいい)","definition":"diễn biến, quá trình","example":"事件の経緯を説明した。","topic":"Abstract Nouns"},
  {"id":"nf-831","word":"基準 (きじゅん)","definition":"tiêu chuẩn","example":"安全基準を満たす。","topic":"Abstract Nouns"},
  {"id":"nf-832","word":"指標 (しひょう)","definition":"chỉ tiêu, chỉ số","example":"経済の重要な指標を確認する。","topic":"Abstract Nouns"},
  {"id":"nf-833","word":"成果 (せいか)","definition":"thành quả","example":"研究の成果を発表した。","topic":"Abstract Nouns"},
  {"id":"nf-834","word":"手段 (しゅだん)","definition":"phương tiện, biện pháp","example":"目的を達成するための手段を考える。","topic":"Abstract Nouns"},
  {"id":"nf-835","word":"措置 (そち)","definition":"biện pháp, xử lý","example":"緊急措置をとる。","topic":"Abstract Nouns"},
  {"id":"nf-836","word":"意義 (いぎ)","definition":"ý nghĩa","example":"この研究の意義は大きい。","topic":"Abstract Nouns"},
  {"id":"nf-837","word":"価値 (かち)","definition":"giá trị","example":"歴史的な価値がある建物。","topic":"Abstract Nouns"},
  {"id":"nf-838","word":"特徴 (とくちょう)","definition":"đặc trưng, đặc điểm","example":"日本料理の特徴は繊細さだ。","topic":"Abstract Nouns"},
  {"id":"nf-839","word":"構造 (こうぞう)","definition":"cấu trúc","example":"社会の構造が変わりつつある。","topic":"Abstract Nouns"},
  {"id":"nf-840","word":"仕組み (しくみ)","definition":"cơ chế, cấu tạo","example":"年金制度の仕組みを理解する。","topic":"Abstract Nouns"},
  {"id":"nf-841","word":"原則 (げんそく)","definition":"nguyên tắc","example":"原則として残業は禁止だ。","topic":"Abstract Nouns"},
  {"id":"nf-842","word":"見通し (みとおし)","definition":"triển vọng, dự báo","example":"経済の見通しは明るい。","topic":"Abstract Nouns"},
  {"id":"nf-843","word":"見解 (けんかい)","definition":"kiến giải, quan điểm","example":"専門家の見解を聞く。","topic":"Abstract Nouns"},
  {"id":"nf-844","word":"動機 (どうき)","definition":"động cơ","example":"犯行の動機を調べる。","topic":"Abstract Nouns"},
  {"id":"nf-845","word":"意図 (いと)","definition":"ý đồ, chủ đích","example":"相手の意図を読み取る。","topic":"Abstract Nouns"},
  {"id":"nf-846","word":"信念 (しんねん)","definition":"tín niệm, niềm tin","example":"自分の信念を貫く。","topic":"Abstract Nouns"},
  {"id":"nf-847","word":"覚悟 (かくご)","definition":"sự quyết tâm, chuẩn bị tinh thần","example":"最悪の事態を覚悟する。","topic":"Abstract Nouns"},
  {"id":"nf-848","word":"志 (こころざし)","definition":"chí hướng, hoài bão","example":"高い志を持って努力する。","topic":"Abstract Nouns"},
  {"id":"nf-849","word":"偏見 (へんけん)","definition":"thành kiến, thiên kiến","example":"偏見をなくす努力をする。","topic":"Abstract Nouns"},
  {"id":"nf-850","word":"矛盾 (むじゅん)","definition":"mâu thuẫn","example":"理論に矛盾がある。","topic":"Abstract Nouns"},
  {"id":"nf-851","word":"葛藤 (かっとう)","definition":"mâu thuẫn nội tâm, giằng xé","example":"理想と現実の間で葛藤する。","topic":"Abstract Nouns"},
  {"id":"nf-852","word":"合意 (ごうい)","definition":"đồng ý, thỏa thuận","example":"両者の合意が得られた。","topic":"Abstract Nouns"},
  {"id":"nf-853","word":"妥協 (だきょう)","definition":"thỏa hiệp","example":"お互いに妥協することが大事だ。","topic":"Abstract Nouns"},
  {"id":"nf-854","word":"余裕 (よゆう)","definition":"sự dư dả, thong thả","example":"時間に余裕を持って出発する。","topic":"Abstract Nouns"},
  {"id":"nf-855","word":"欠陥 (けっかん)","definition":"khiếm khuyết, lỗi","example":"製品に欠陥が見つかった。","topic":"Abstract Nouns"},
  {"id":"nf-856","word":"弱点 (じゃくてん)","definition":"điểm yếu","example":"自分の弱点を克服する。","topic":"Abstract Nouns"},
  {"id":"nf-857","word":"長所 (ちょうしょ)","definition":"ưu điểm, sở trường","example":"自分の長所を活かす。","topic":"Abstract Nouns"},
  {"id":"nf-858","word":"短所 (たんしょ)","definition":"khuyết điểm, sở đoản","example":"短所を改善する努力をする。","topic":"Abstract Nouns"},
  {"id":"nf-859","word":"因果 (いんが)","definition":"nhân quả","example":"原因と結果の因果関係を調べる。","topic":"Abstract Nouns"},
  {"id":"nf-860","word":"連鎖 (れんさ)","definition":"chuỗi, liên hoàn","example":"悪い連鎖を断ち切る。","topic":"Abstract Nouns"},
  {"id":"nf-861","word":"循環 (じゅんかん)","definition":"tuần hoàn","example":"資源の循環を促進する。","topic":"Abstract Nouns"},
  {"id":"nf-862","word":"均衡 (きんこう)","definition":"cân bằng","example":"需要と供給の均衡を保つ。","topic":"Abstract Nouns"},
  {"id":"nf-863","word":"飽和 (ほうわ)","definition":"bão hòa","example":"市場が飽和状態にある。","topic":"Abstract Nouns"},
  {"id":"nf-864","word":"衝撃 (しょうげき)","definition":"chấn động, sốc","example":"そのニュースは衝撃的だった。","topic":"Abstract Nouns"},
  {"id":"nf-865","word":"波紋 (はもん)","definition":"gợn sóng, ảnh hưởng lan rộng","example":"発言が大きな波紋を呼んだ。","topic":"Abstract Nouns"},
  {"id":"nf-866","word":"摩擦 (まさつ)","definition":"ma sát, xung đột","example":"貿易摩擦が続いている。","topic":"Abstract Nouns"},
  {"id":"nf-867","word":"恩恵 (おんけい)","definition":"ân huệ, lợi ích","example":"技術の発展の恩恵を受ける。","topic":"Abstract Nouns"},
  {"id":"nf-868","word":"弊害 (へいがい)","definition":"tệ hại, hậu quả xấu","example":"過度な競争の弊害が出ている。","topic":"Abstract Nouns"},
  {"id":"nf-869","word":"功績 (こうせき)","definition":"công tích, công lao","example":"彼の功績は非常に大きい。","topic":"Abstract Nouns"},
  {"id":"nf-870","word":"限界 (げんかい)","definition":"giới hạn","example":"体力の限界を感じた。","topic":"Abstract Nouns"},
  {"id":"nf-871","word":"可能性 (かのうせい)","definition":"khả năng","example":"成功の可能性は高い。","topic":"Abstract Nouns"},
  {"id":"nf-872","word":"実態 (じったい)","definition":"thực trạng","example":"労働環境の実態を調査する。","topic":"Abstract Nouns"},
  {"id":"nf-873","word":"趣旨 (しゅし)","definition":"ý chính, mục đích","example":"提案の趣旨を説明する。","topic":"Abstract Nouns"},
  {"id":"nf-874","word":"概要 (がいよう)","definition":"tổng quan, khái quát","example":"報告書の概要をまとめる。","topic":"Abstract Nouns"},
  {"id":"nf-875","word":"詳細 (しょうさい)","definition":"chi tiết","example":"詳細は後日お知らせします。","topic":"Abstract Nouns"},

  # === Daily Advanced - 60 cards ===
  {"id":"nf-876","word":"辛うじて (かろうじて)","definition":"một cách vất vả, chỉ vừa đủ","example":"辛うじて合格した。","topic":"Daily Advanced"},
  {"id":"nf-877","word":"あくまで","definition":"đến cùng, nhất quyết","example":"あくまで自分の意見を貫いた。","topic":"Daily Advanced"},
  {"id":"nf-878","word":"一応 (いちおう)","definition":"tạm thời, cho có","example":"一応確認しておきます。","topic":"Daily Advanced"},
  {"id":"nf-879","word":"一概に (いちがいに)","definition":"nhất khái, đồng loạt","example":"一概にそうとは言えない。","topic":"Daily Advanced"},
  {"id":"nf-880","word":"一方的 (いっぽうてき)","definition":"một chiều, đơn phương","example":"一方的に話を進めないでください。","topic":"Daily Advanced"},
  {"id":"nf-881","word":"大いに (おおいに)","definition":"rất nhiều, vô cùng","example":"大いに期待している。","topic":"Daily Advanced"},
  {"id":"nf-882","word":"概ね (おおむね)","definition":"đại khái, nhìn chung","example":"計画は概ね順調に進んでいる。","topic":"Daily Advanced"},
  {"id":"nf-883","word":"かえって","definition":"ngược lại, trái lại","example":"薬を飲んだら、かえって悪くなった。","topic":"Daily Advanced"},
  {"id":"nf-884","word":"果たして (はたして)","definition":"quả nhiên, liệu rằng","example":"果たして彼は来るだろうか。","topic":"Daily Advanced"},
  {"id":"nf-885","word":"仮に (かりに)","definition":"giả sử, nếu giả sử","example":"仮に失敗しても、諦めない。","topic":"Daily Advanced"},
  {"id":"nf-886","word":"極めて (きわめて)","definition":"cực kỳ, vô cùng","example":"極めて重要な問題だ。","topic":"Daily Advanced"},
  {"id":"nf-887","word":"さすがに","definition":"quả thật, xứng đáng","example":"さすがにプロだけあって上手だ。","topic":"Daily Advanced"},
  {"id":"nf-888","word":"しばしば","definition":"thường xuyên, hay","example":"この地域ではしばしば地震が起きる。","topic":"Daily Advanced"},
  {"id":"nf-889","word":"少なくとも (すくなくとも)","definition":"ít nhất","example":"少なくとも30分はかかる。","topic":"Daily Advanced"},
  {"id":"nf-890","word":"すなわち","definition":"tức là, nghĩa là","example":"彼は社長、すなわち最高責任者だ。","topic":"Daily Advanced"},
  {"id":"nf-891","word":"たちまち","definition":"ngay lập tức, bỗng chốc","example":"噂はたちまち広がった。","topic":"Daily Advanced"},
  {"id":"nf-892","word":"単に (たんに)","definition":"chỉ đơn giản là, chỉ","example":"単に忙しかっただけです。","topic":"Daily Advanced"},
  {"id":"nf-893","word":"とにかく","definition":"dù sao đi nữa, trước hết","example":"とにかくやってみよう。","topic":"Daily Advanced"},
  {"id":"nf-894","word":"なお","definition":"hơn nữa, ngoài ra (văn viết)","example":"なお、詳細は後日お知らせします。","topic":"Daily Advanced"},
  {"id":"nf-895","word":"むしろ","definition":"thà, đúng hơn là","example":"行くよりむしろ家にいたい。","topic":"Daily Advanced"},
  {"id":"nf-896","word":"もっぱら","definition":"chuyên, chủ yếu","example":"彼はもっぱら研究に専念している。","topic":"Daily Advanced"},
  {"id":"nf-897","word":"やがて","definition":"rồi thì, chẳng bao lâu","example":"やがて春が来るだろう。","topic":"Daily Advanced"},
  {"id":"nf-898","word":"ようやく","definition":"cuối cùng cũng, rốt cuộc","example":"ようやく目標を達成した。","topic":"Daily Advanced"},
  {"id":"nf-899","word":"予め (あらかじめ)","definition":"trước, sẵn","example":"予めご了承ください。","topic":"Daily Advanced"},
  {"id":"nf-900","word":"いずれ","definition":"sớm muộn gì, trong số","example":"いずれ結果が出るだろう。","topic":"Daily Advanced"},
  {"id":"nf-901","word":"万が一 (まんがいち)","definition":"lỡ, vạn nhất","example":"万が一に備えて保険に入る。","topic":"Daily Advanced"},
  {"id":"nf-902","word":"ことごとく","definition":"tất cả, mọi thứ","example":"計画はことごとく失敗した。","topic":"Daily Advanced"},
  {"id":"nf-903","word":"おのずと","definition":"tự nhiên, tự mình","example":"努力すればおのずと結果はついてくる。","topic":"Daily Advanced"},
  {"id":"nf-904","word":"ひたすら","definition":"chỉ một mực, mải miết","example":"合格を目指してひたすら勉強した。","topic":"Daily Advanced"},
  {"id":"nf-905","word":"たまたま","definition":"tình cờ","example":"たまたま友達に会った。","topic":"Daily Advanced"},
  {"id":"nf-906","word":"いきなり","definition":"đột ngột, bất ngờ","example":"いきなり質問されて驚いた。","topic":"Daily Advanced"},
  {"id":"nf-907","word":"ぜひ","definition":"nhất định, xin hãy","example":"ぜひ遊びに来てください。","topic":"Daily Advanced"},
  {"id":"nf-908","word":"何しろ (なにしろ)","definition":"bởi vì, dù sao thì","example":"何しろ初めてだから仕方がない。","topic":"Daily Advanced"},
  {"id":"nf-909","word":"せっかく","definition":"khó khăn lắm mới, công sức","example":"せっかく来たのだから楽しもう。","topic":"Daily Advanced"},
  {"id":"nf-910","word":"わざわざ","definition":"cất công, đặc biệt","example":"わざわざ来てくれてありがとう。","topic":"Daily Advanced"},
  {"id":"nf-911","word":"まさか","definition":"không ngờ, chẳng lẽ","example":"まさか彼が犯人だとは思わなかった。","topic":"Daily Advanced"},
  {"id":"nf-912","word":"所詮 (しょせん)","definition":"xét cho cùng, rốt cuộc","example":"所詮、素人には無理だ。","topic":"Daily Advanced"},
  {"id":"nf-913","word":"何気なく (なにげなく)","definition":"không chủ ý, tự nhiên","example":"何気なく言った言葉が相手を傷つけた。","topic":"Daily Advanced"},
  {"id":"nf-914","word":"明らかに (あきらかに)","definition":"rõ ràng, hiển nhiên","example":"明らかに間違っている。","topic":"Daily Advanced"},
  {"id":"nf-915","word":"必ずしも (かならずしも)","definition":"không nhất thiết","example":"高いものが必ずしも良いとは限らない。","topic":"Daily Advanced"},
  {"id":"nf-916","word":"しきりに","definition":"liên tục, không ngừng","example":"彼はしきりに時計を気にしていた。","topic":"Daily Advanced"},
  {"id":"nf-917","word":"つくづく","definition":"thấm thía, sâu sắc","example":"健康の大切さをつくづく感じた。","topic":"Daily Advanced"},
  {"id":"nf-918","word":"ろくに","definition":"không đàng hoàng (phủ định)","example":"ろくに寝ていないので眠い。","topic":"Daily Advanced"},
  {"id":"nf-919","word":"めったに","definition":"hiếm khi","example":"彼はめったに怒らない。","topic":"Daily Advanced"},
  {"id":"nf-920","word":"たびたび","definition":"nhiều lần","example":"たびたびご迷惑をおかけします。","topic":"Daily Advanced"},
  {"id":"nf-921","word":"いっそ","definition":"thà rằng, chi bằng","example":"いっそ全部やり直した方がいい。","topic":"Daily Advanced"},
  {"id":"nf-922","word":"到底 (とうてい)","definition":"dù thế nào cũng (phủ định)","example":"到底間に合わない。","topic":"Daily Advanced"},
  {"id":"nf-923","word":"案の定 (あんのじょう)","definition":"quả nhiên, đúng như dự đoán","example":"案の定、彼は遅刻してきた。","topic":"Daily Advanced"},
  {"id":"nf-924","word":"幸い (さいわい)","definition":"may mắn thay","example":"幸い、大きな被害はなかった。","topic":"Daily Advanced"},
  {"id":"nf-925","word":"あえて","definition":"dám, cố tình","example":"あえて危険を冒す。","topic":"Daily Advanced"},
  {"id":"nf-926","word":"いわば","definition":"có thể nói là","example":"彼はいわば天才だ。","topic":"Daily Advanced"},
  {"id":"nf-927","word":"とかく","definition":"hay, thường hay","example":"人はとかく他人の欠点を見つけがちだ。","topic":"Daily Advanced"},
  {"id":"nf-928","word":"兼ねて (かねて)","definition":"kết hợp, kiêm","example":"散歩を兼ねて買い物に行く。","topic":"Daily Advanced"},
  {"id":"nf-929","word":"予め (あらかじめ)","definition":"trước, chuẩn bị sẵn","example":"予め計画を立てておく。","topic":"Daily Advanced"},
  {"id":"nf-930","word":"いまだに","definition":"cho đến bây giờ vẫn","example":"いまだに返事が来ない。","topic":"Daily Advanced"},
  {"id":"nf-931","word":"なるほど","definition":"à ra vậy, quả đúng thế","example":"なるほど、そういうことか。","topic":"Daily Advanced"},
  {"id":"nf-932","word":"たとえ","definition":"cho dù, dù cho","example":"たとえ失敗しても後悔しない。","topic":"Daily Advanced"},
  {"id":"nf-933","word":"しかも","definition":"hơn nữa, lại còn","example":"安いし、しかも品質も良い。","topic":"Daily Advanced"},
  {"id":"nf-934","word":"ところが","definition":"tuy nhiên, nhưng mà","example":"晴れると思ったが、ところが雨が降った。","topic":"Daily Advanced"},
  {"id":"nf-935","word":"そもそも","definition":"vốn dĩ, ngay từ đầu","example":"そもそも計画に無理があった。","topic":"Daily Advanced"},

  # === Science/Environment - 70 cards ===
  {"id":"nf-936","word":"酸素 (さんそ)","definition":"oxy","example":"植物は酸素を供給する。","topic":"Science"},
  {"id":"nf-937","word":"二酸化炭素 (にさんかたんそ)","definition":"CO2, carbon dioxide","example":"二酸化炭素の排出を減らす。","topic":"Science"},
  {"id":"nf-938","word":"窒素 (ちっそ)","definition":"nitơ","example":"空気の約78%は窒素だ。","topic":"Science"},
  {"id":"nf-939","word":"水素 (すいそ)","definition":"hydro","example":"水素エネルギーの開発。","topic":"Science"},
  {"id":"nf-940","word":"分子 (ぶんし)","definition":"phân tử","example":"水は酸素と水素の分子でできている。","topic":"Science"},
  {"id":"nf-941","word":"原子 (げんし)","definition":"nguyên tử","example":"原子力発電所を建設する。","topic":"Science"},
  {"id":"nf-942","word":"細胞 (さいぼう)","definition":"tế bào","example":"人体は約37兆の細胞で構成されている。","topic":"Science"},
  {"id":"nf-943","word":"遺伝子 (いでんし)","definition":"gen, gien","example":"遺伝子の研究が進んでいる。","topic":"Science"},
  {"id":"nf-944","word":"微生物 (びせいぶつ)","definition":"vi sinh vật","example":"微生物が土壌を豊かにする。","topic":"Science"},
  {"id":"nf-945","word":"進化 (しんか)","definition":"tiến hóa","example":"生物は環境に適応して進化する。","topic":"Science"},
  {"id":"nf-946","word":"絶滅 (ぜつめつ)","definition":"tuyệt chủng","example":"多くの種が絶滅の危機にある。","topic":"Science"},
  {"id":"nf-947","word":"生態系 (せいたいけい)","definition":"hệ sinh thái","example":"森林の生態系を守る。","topic":"Science"},
  {"id":"nf-948","word":"光合成 (こうごうせい)","definition":"quang hợp","example":"植物は光合成で栄養を作る。","topic":"Science"},
  {"id":"nf-949","word":"免疫 (めんえき)","definition":"miễn dịch","example":"免疫力を高める。","topic":"Science"},
  {"id":"nf-950","word":"症状 (しょうじょう)","definition":"triệu chứng","example":"風邪の症状が出ている。","topic":"Science"},
  {"id":"nf-951","word":"診断 (しんだん)","definition":"chẩn đoán","example":"早期診断が重要だ。","topic":"Science"},
  {"id":"nf-952","word":"治療 (ちりょう)","definition":"điều trị","example":"新しい治療法が開発された。","topic":"Science"},
  {"id":"nf-953","word":"副作用 (ふくさよう)","definition":"tác dụng phụ","example":"この薬には副作用がある。","topic":"Science"},
  {"id":"nf-954","word":"感染 (かんせん)","definition":"nhiễm, lây nhiễm","example":"感染を予防する対策をとる。","topic":"Science"},
  {"id":"nf-955","word":"ワクチン","definition":"vắc-xin","example":"インフルエンザのワクチンを打つ。","topic":"Science"},
  {"id":"nf-956","word":"太陽光 (たいようこう)","definition":"ánh sáng mặt trời","example":"太陽光発電を導入する。","topic":"Science"},
  {"id":"nf-957","word":"風力 (ふうりょく)","definition":"sức gió","example":"風力発電が普及している。","topic":"Science"},
  {"id":"nf-958","word":"原子力 (げんしりょく)","definition":"năng lượng hạt nhân","example":"原子力発電の安全性が問われている。","topic":"Science"},
  {"id":"nf-959","word":"排出 (はいしゅつ)","definition":"thải ra, phát thải","example":"工場からの排出ガスを規制する。","topic":"Science"},
  {"id":"nf-960","word":"汚染 (おせん)","definition":"ô nhiễm","example":"河川の汚染が深刻だ。","topic":"Science"},
  {"id":"nf-961","word":"浄化 (じょうか)","definition":"thanh lọc, tịnh hóa","example":"水を浄化する技術。","topic":"Science"},
  {"id":"nf-962","word":"再利用 (さいりよう)","definition":"tái sử dụng","example":"ペットボトルを再利用する。","topic":"Science"},
  {"id":"nf-963","word":"分別 (ぶんべつ)","definition":"phân loại (rác)","example":"ゴミを分別して出す。","topic":"Science"},
  {"id":"nf-964","word":"廃棄物 (はいきぶつ)","definition":"chất thải, rác thải","example":"産業廃棄物の処理が課題だ。","topic":"Science"},
  {"id":"nf-965","word":"持続可能 (じぞくかのう)","definition":"bền vững","example":"持続可能な社会を目指す。","topic":"Science"},
  {"id":"nf-966","word":"生物多様性 (せいぶつたようせい)","definition":"đa dạng sinh học","example":"生物多様性を保全する。","topic":"Science"},
  {"id":"nf-967","word":"気候変動 (きこうへんどう)","definition":"biến đổi khí hậu","example":"気候変動が農業に影響を与えている。","topic":"Science"},
  {"id":"nf-968","word":"砂漠化 (さばくか)","definition":"sa mạc hóa","example":"砂漠化の進行を食い止める。","topic":"Science"},
  {"id":"nf-969","word":"森林伐採 (しんりんばっさい)","definition":"chặt phá rừng","example":"森林伐採が環境破壊の原因だ。","topic":"Science"},
  {"id":"nf-970","word":"オゾン層 (オゾンそう)","definition":"tầng ozone","example":"オゾン層の破壊が進んでいる。","topic":"Science"},
  {"id":"nf-971","word":"紫外線 (しがいせん)","definition":"tia cực tím","example":"紫外線から肌を守る。","topic":"Science"},
  {"id":"nf-972","word":"放射線 (ほうしゃせん)","definition":"bức xạ, phóng xạ","example":"放射線の量を測定する。","topic":"Science"},
  {"id":"nf-973","word":"化石燃料 (かせきねんりょう)","definition":"nhiên liệu hóa thạch","example":"化石燃料に頼らない社会を目指す。","topic":"Science"},
  {"id":"nf-974","word":"温室効果 (おんしつこうか)","definition":"hiệu ứng nhà kính","example":"温室効果ガスを削減する。","topic":"Science"},
  {"id":"nf-975","word":"海面上昇 (かいめんじょうしょう)","definition":"mực nước biển dâng","example":"海面上昇が島国を脅かしている。","topic":"Science"},
  {"id":"nf-976","word":"地震 (じしん)","definition":"động đất","example":"日本は地震が多い国だ。","topic":"Science"},
  {"id":"nf-977","word":"噴火 (ふんか)","definition":"phun trào (núi lửa)","example":"火山が噴火した。","topic":"Science"},
  {"id":"nf-978","word":"津波 (つなみ)","definition":"sóng thần","example":"地震の後に津波が来た。","topic":"Science"},
  {"id":"nf-979","word":"干ばつ (かんばつ)","definition":"hạn hán","example":"干ばつで農作物が被害を受けた。","topic":"Science"},
  {"id":"nf-980","word":"洪水 (こうずい)","definition":"lũ lụt","example":"大雨で洪水が発生した。","topic":"Science"},
  {"id":"nf-981","word":"天然 (てんねん)","definition":"thiên nhiên, tự nhiên","example":"天然の素材を使う。","topic":"Science"},
  {"id":"nf-982","word":"人工 (じんこう)","definition":"nhân tạo","example":"人工知能が急速に発展している。","topic":"Science"},
  {"id":"nf-983","word":"実験 (じっけん)","definition":"thí nghiệm","example":"新薬の実験を行う。","topic":"Science"},
  {"id":"nf-984","word":"仮説 (かせつ)","definition":"giả thuyết","example":"仮説を検証する。","topic":"Science"},
  {"id":"nf-985","word":"観測 (かんそく)","definition":"quan trắc, quan sát","example":"天体を観測する。","topic":"Science"},
  {"id":"nf-986","word":"数値 (すうち)","definition":"số trị, con số","example":"正確な数値を出す。","topic":"Science"},
  {"id":"nf-987","word":"統計 (とうけい)","definition":"thống kê","example":"統計データを分析する。","topic":"Science"},
  {"id":"nf-988","word":"比率 (ひりつ)","definition":"tỷ lệ","example":"女性の比率が増えている。","topic":"Science"},
  {"id":"nf-989","word":"密度 (みつど)","definition":"mật độ","example":"東京は人口密度が高い。","topic":"Science"},
  {"id":"nf-990","word":"体積 (たいせき)","definition":"thể tích","example":"水の体積を計算する。","topic":"Science"},
  {"id":"nf-991","word":"重力 (じゅうりょく)","definition":"trọng lực","example":"月の重力は地球の6分の1だ。","topic":"Science"},
  {"id":"nf-992","word":"磁場 (じば)","definition":"từ trường","example":"地球には磁場がある。","topic":"Science"},
  {"id":"nf-993","word":"波長 (はちょう)","definition":"bước sóng","example":"光の波長によって色が変わる。","topic":"Science"},
  {"id":"nf-994","word":"周波数 (しゅうはすう)","definition":"tần số","example":"ラジオの周波数を合わせる。","topic":"Science"},
  {"id":"nf-995","word":"導体 (どうたい)","definition":"vật dẫn","example":"金属は電気の導体だ。","topic":"Science"},
  {"id":"nf-996","word":"合金 (ごうきん)","definition":"hợp kim","example":"チタン合金は軽くて丈夫だ。","topic":"Science"},
  {"id":"nf-997","word":"半導体 (はんどうたい)","definition":"bán dẫn","example":"半導体産業が急成長している。","topic":"Science"},
  {"id":"nf-998","word":"繊維 (せんい)","definition":"sợi, chất xơ","example":"化学繊維で作られた服。","topic":"Science"},
  {"id":"nf-999","word":"合成 (ごうせい)","definition":"tổng hợp","example":"合成樹脂を使用する。","topic":"Science"},
  {"id":"nf-1000","word":"化合物 (かごうぶつ)","definition":"hợp chất","example":"水は化合物の一つだ。","topic":"Science"},
  {"id":"nf-1001","word":"酸性 (さんせい)","definition":"tính axit","example":"酸性雨が森林を枯らす。","topic":"Science"},
  {"id":"nf-1002","word":"アルカリ性","definition":"tính kiềm","example":"石鹸はアルカリ性だ。","topic":"Science"},
  {"id":"nf-1003","word":"溶液 (ようえき)","definition":"dung dịch","example":"化学溶液を作る。","topic":"Science"},
  {"id":"nf-1004","word":"触媒 (しょくばい)","definition":"chất xúc tác","example":"触媒を使って反応を早める。","topic":"Science"},
  {"id":"nf-1005","word":"濃度 (のうど)","definition":"nồng độ","example":"酸素の濃度を測定する。","topic":"Science"}
]

print(f"Total cards in batch 2: {len(cards)}")

with open('/home/adminstrator/code/test/language-app/src/data/n2/flashcards-batch2.json', 'w', encoding='utf-8') as f:
    json.dump(cards, f, ensure_ascii=False, indent=2)

print("Done! Created flashcards-batch2.json with 500 cards.")
