import json

# Generate 500 N2 flashcards - batch 3 (nf-1006 to nf-1505)
cards = [
  # === Verbs (N2 Essential) - 100 cards ===
  {"id":"nf-1006","word":"勧める (すすめる)","definition":"khuyên, đề nghị","example":"友人にこの本を勧めた。","topic":"Verbs N2"},
  {"id":"nf-1007","word":"催す (もよおす)","definition":"tổ chức, cảm thấy","example":"イベントを催す。","topic":"Verbs N2"},
  {"id":"nf-1008","word":"恵まれる (めぐまれる)","definition":"được ban phước, may mắn","example":"天候に恵まれた。","topic":"Verbs N2"},
  {"id":"nf-1009","word":"抱える (かかえる)","definition":"ôm, gánh chịu","example":"多くの問題を抱えている。","topic":"Verbs N2"},
  {"id":"nf-1010","word":"傾く (かたむく)","definition":"nghiêng, có xu hướng","example":"建物が傾いている。","topic":"Verbs N2"},
  {"id":"nf-1011","word":"兼ねる (かねる)","definition":"kiêm nhiệm, khó có thể","example":"社長が会長を兼ねる。","topic":"Verbs N2"},
  {"id":"nf-1012","word":"覆す (くつがえす)","definition":"lật đổ, đảo ngược","example":"常識を覆す発明。","topic":"Verbs N2"},
  {"id":"nf-1013","word":"悔やむ (くやむ)","definition":"hối hận, ân hận","example":"あの時の判断を悔やんでいる。","topic":"Verbs N2"},
  {"id":"nf-1014","word":"異なる (ことなる)","definition":"khác biệt","example":"文化が異なる国で暮らす。","topic":"Verbs N2"},
  {"id":"nf-1015","word":"妨げる (さまたげる)","definition":"cản trở, ngăn cản","example":"交通を妨げる行為。","topic":"Verbs N2"},
  {"id":"nf-1016","word":"遮る (さえぎる)","definition":"che chắn, cắt ngang","example":"彼の話を遮った。","topic":"Verbs N2"},
  {"id":"nf-1017","word":"損なう (そこなう)","definition":"làm hỏng, gây hại","example":"健康を損なう恐れがある。","topic":"Verbs N2"},
  {"id":"nf-1018","word":"携わる (たずさわる)","definition":"tham gia, dính líu","example":"教育に携わる仕事をしている。","topic":"Verbs N2"},
  {"id":"nf-1019","word":"漂う (ただよう)","definition":"trôi nổi, bao phủ","example":"いい匂いが漂っている。","topic":"Verbs N2"},
  {"id":"nf-1020","word":"費やす (ついやす)","definition":"tiêu tốn, dành","example":"多くの時間を費やした。","topic":"Verbs N2"},
  {"id":"nf-1021","word":"募る (つのる)","definition":"tuyển, tăng dần","example":"ボランティアを募る。","topic":"Verbs N2"},
  {"id":"nf-1022","word":"潰す (つぶす)","definition":"nghiền nát, phá hủy","example":"時間を潰す方法を考える。","topic":"Verbs N2"},
  {"id":"nf-1023","word":"突っ込む (つっこむ)","definition":"lao vào, xen vào","example":"話に突っ込みを入れる。","topic":"Verbs N2"},
  {"id":"nf-1024","word":"唱える (となえる)","definition":"đề xướng, đọc","example":"新しい理論を唱える。","topic":"Verbs N2"},
  {"id":"nf-1025","word":"伴う (ともなう)","definition":"đi kèm, kèm theo","example":"危険を伴う作業。","topic":"Verbs N2"},
  {"id":"nf-1026","word":"怠る (おこたる)","definition":"lơ là, bê trễ","example":"点検を怠ったために事故が起きた。","topic":"Verbs N2"},
  {"id":"nf-1027","word":"脅かす (おびやかす)","definition":"đe dọa","example":"環境破壊が生態系を脅かしている。","topic":"Verbs N2"},
  {"id":"nf-1028","word":"補う (おぎなう)","definition":"bổ sung, bù đắp","example":"不足を補う。","topic":"Verbs N2"},
  {"id":"nf-1029","word":"悟る (さとる)","definition":"nhận ra, giác ngộ","example":"自分の過ちを悟った。","topic":"Verbs N2"},
  {"id":"nf-1030","word":"占める (しめる)","definition":"chiếm","example":"女性が全体の40%を占めている。","topic":"Verbs N2"},
  {"id":"nf-1031","word":"背く (そむく)","definition":"quay lưng, phản bội","example":"親の期待に背く。","topic":"Verbs N2"},
  {"id":"nf-1032","word":"遂げる (とげる)","definition":"đạt được, hoàn thành","example":"目的を遂げた。","topic":"Verbs N2"},
  {"id":"nf-1033","word":"挑む (いどむ)","definition":"thách thức, thử sức","example":"新しい課題に挑む。","topic":"Verbs N2"},
  {"id":"nf-1034","word":"潤う (うるおう)","definition":"ẩm ướt, sung túc","example":"雨で大地が潤った。","topic":"Verbs N2"},
  {"id":"nf-1035","word":"賄う (まかなう)","definition":"chi trả, cung cấp","example":"費用を賄う。","topic":"Verbs N2"},
  {"id":"nf-1036","word":"見なす (みなす)","definition":"coi là, xem như","example":"沈黙は同意と見なす。","topic":"Verbs N2"},
  {"id":"nf-1037","word":"養う (やしなう)","definition":"nuôi dưỡng, rèn luyện","example":"家族を養う。","topic":"Verbs N2"},
  {"id":"nf-1038","word":"催促する (さいそくする)","definition":"thúc giục, nhắc nhở","example":"返事を催促された。","topic":"Verbs N2"},
  {"id":"nf-1039","word":"主張する (しゅちょうする)","definition":"chủ trương, khẳng định","example":"自分の意見を主張する。","topic":"Verbs N2"},
  {"id":"nf-1040","word":"強調する (きょうちょうする)","definition":"nhấn mạnh","example":"安全の重要性を強調した。","topic":"Verbs N2"},
  {"id":"nf-1041","word":"否定する (ひていする)","definition":"phủ định","example":"噂を否定した。","topic":"Verbs N2"},
  {"id":"nf-1042","word":"肯定する (こうていする)","definition":"khẳng định","example":"彼の意見を肯定する。","topic":"Verbs N2"},
  {"id":"nf-1043","word":"批判する (ひはんする)","definition":"phê phán","example":"政府の政策を批判する。","topic":"Verbs N2"},
  {"id":"nf-1044","word":"評価する (ひょうかする)","definition":"đánh giá","example":"社員の能力を評価する。","topic":"Verbs N2"},
  {"id":"nf-1045","word":"区別する (くべつする)","definition":"phân biệt","example":"事実と意見を区別する。","topic":"Verbs N2"},
  {"id":"nf-1046","word":"分類する (ぶんるいする)","definition":"phân loại","example":"データを分類する。","topic":"Verbs N2"},
  {"id":"nf-1047","word":"統合する (とうごうする)","definition":"tích hợp, thống nhất","example":"二つのシステムを統合する。","topic":"Verbs N2"},
  {"id":"nf-1048","word":"排除する (はいじょする)","definition":"loại trừ","example":"危険要素を排除する。","topic":"Verbs N2"},
  {"id":"nf-1049","word":"克服する (こくふくする)","definition":"khắc phục","example":"困難を克服する。","topic":"Verbs N2"},
  {"id":"nf-1050","word":"達成する (たっせいする)","definition":"đạt thành","example":"目標を達成した。","topic":"Verbs N2"},
  {"id":"nf-1051","word":"実施する (じっしする)","definition":"thực thi","example":"新しい制度を実施する。","topic":"Verbs N2"},
  {"id":"nf-1052","word":"設置する (せっちする)","definition":"lắp đặt, thiết lập","example":"監視カメラを設置する。","topic":"Verbs N2"},
  {"id":"nf-1053","word":"撤回する (てっかいする)","definition":"rút lại, thu hồi","example":"発言を撤回した。","topic":"Verbs N2"},
  {"id":"nf-1054","word":"訂正する (ていせいする)","definition":"đính chính, sửa chữa","example":"誤りを訂正する。","topic":"Verbs N2"},
  {"id":"nf-1055","word":"修正する (しゅうせいする)","definition":"chỉnh sửa","example":"計画を修正した。","topic":"Verbs N2"},
  {"id":"nf-1056","word":"解消する (かいしょうする)","definition":"giải tiêu, xóa bỏ","example":"ストレスを解消する。","topic":"Verbs N2"},
  {"id":"nf-1057","word":"解放する (かいほうする)","definition":"giải phóng","example":"束縛から解放される。","topic":"Verbs N2"},
  {"id":"nf-1058","word":"緩和する (かんわする)","definition":"nới lỏng, giảm bớt","example":"規制を緩和する。","topic":"Verbs N2"},
  {"id":"nf-1059","word":"強化する (きょうかする)","definition":"tăng cường","example":"セキュリティを強化する。","topic":"Verbs N2"},
  {"id":"nf-1060","word":"推進する (すいしんする)","definition":"thúc đẩy, xúc tiến","example":"計画を推進する。","topic":"Verbs N2"},
  {"id":"nf-1061","word":"促す (うながす)","definition":"thúc giục, khuyến khích","example":"行動を促す。","topic":"Verbs N2"},
  {"id":"nf-1062","word":"抑える (おさえる)","definition":"kiềm chế, giữ","example":"感情を抑える。","topic":"Verbs N2"},
  {"id":"nf-1063","word":"覆う (おおう)","definition":"che phủ","example":"雪が山を覆っている。","topic":"Verbs N2"},
  {"id":"nf-1064","word":"培う (つちかう)","definition":"bồi dưỡng, vun đắp","example":"長年培ってきた技術。","topic":"Verbs N2"},
  {"id":"nf-1065","word":"据える (すえる)","definition":"đặt, lắp đặt","example":"目標を据える。","topic":"Verbs N2"},
  {"id":"nf-1066","word":"潜む (ひそむ)","definition":"ẩn náu, tiềm ẩn","example":"危険が潜んでいる。","topic":"Verbs N2"},
  {"id":"nf-1067","word":"揺るがす (ゆるがす)","definition":"làm lung lay","example":"社会の基盤を揺るがす事件。","topic":"Verbs N2"},
  {"id":"nf-1068","word":"担う (になう)","definition":"gánh vác, đảm đương","example":"重要な役割を担う。","topic":"Verbs N2"},
  {"id":"nf-1069","word":"備える (そなえる)","definition":"chuẩn bị, trang bị","example":"災害に備える。","topic":"Verbs N2"},
  {"id":"nf-1070","word":"率いる (ひきいる)","definition":"dẫn dắt, lãnh đạo","example":"チームを率いる。","topic":"Verbs N2"},
  {"id":"nf-1071","word":"育む (はぐくむ)","definition":"nuôi dưỡng, ươm mầm","example":"才能を育む環境。","topic":"Verbs N2"},
  {"id":"nf-1072","word":"賭ける (かける)","definition":"đặt cược","example":"人生を賭けて挑戦する。","topic":"Verbs N2"},
  {"id":"nf-1073","word":"省みる (かえりみる)","definition":"nhìn lại, tự xét","example":"自分の行動を省みる。","topic":"Verbs N2"},
  {"id":"nf-1074","word":"試みる (こころみる)","definition":"thử, cố gắng","example":"新しい方法を試みる。","topic":"Verbs N2"},
  {"id":"nf-1075","word":"見込む (みこむ)","definition":"dự kiến, kỳ vọng","example":"利益の増加を見込む。","topic":"Verbs N2"},
  {"id":"nf-1076","word":"要する (ようする)","definition":"cần, đòi hỏi","example":"修理に3日を要する。","topic":"Verbs N2"},
  {"id":"nf-1077","word":"及ぶ (およぶ)","definition":"đến, ảnh hưởng đến","example":"被害が広範囲に及んだ。","topic":"Verbs N2"},
  {"id":"nf-1078","word":"至る (いたる)","definition":"đến, đi đến","example":"合意に至った。","topic":"Verbs N2"},
  {"id":"nf-1079","word":"生じる (しょうじる)","definition":"phát sinh, xảy ra","example":"問題が生じた。","topic":"Verbs N2"},
  {"id":"nf-1080","word":"滅びる (ほろびる)","definition":"diệt vong, sụp đổ","example":"文明が滅びる。","topic":"Verbs N2"},
  {"id":"nf-1081","word":"栄える (さかえる)","definition":"thịnh vượng, phồn vinh","example":"この地域は商業で栄えた。","topic":"Verbs N2"},
  {"id":"nf-1082","word":"衰える (おとろえる)","definition":"suy yếu, suy tàn","example":"体力が衰えてきた。","topic":"Verbs N2"},
  {"id":"nf-1083","word":"偏る (かたよる)","definition":"thiên lệch, không cân bằng","example":"食事が偏っている。","topic":"Verbs N2"},
  {"id":"nf-1084","word":"秀でる (ひいでる)","definition":"xuất sắc, nổi trội","example":"彼は数学に秀でている。","topic":"Verbs N2"},
  {"id":"nf-1085","word":"慕う (したう)","definition":"ngưỡng mộ, yêu mến","example":"多くの人に慕われている。","topic":"Verbs N2"},
  {"id":"nf-1086","word":"悼む (いたむ)","definition":"thương tiếc, tưởng niệm","example":"亡くなった友人を悼む。","topic":"Verbs N2"},
  {"id":"nf-1087","word":"誓う (ちかう)","definition":"thề, cam kết","example":"永遠の愛を誓う。","topic":"Verbs N2"},
  {"id":"nf-1088","word":"蓄える (たくわえる)","definition":"tích trữ, dự trữ","example":"食料を蓄える。","topic":"Verbs N2"},
  {"id":"nf-1089","word":"省く (はぶく)","definition":"lược bỏ, tiết kiệm","example":"不要な手続きを省く。","topic":"Verbs N2"},
  {"id":"nf-1090","word":"称える (たたえる)","definition":"ca ngợi, tôn vinh","example":"彼の功績を称える。","topic":"Verbs N2"},
  {"id":"nf-1091","word":"掲げる (かかげる)","definition":"treo, đề ra","example":"目標を掲げる。","topic":"Verbs N2"},
  {"id":"nf-1092","word":"尽くす (つくす)","definition":"cống hiến hết mình","example":"社会のために尽くす。","topic":"Verbs N2"},
  {"id":"nf-1093","word":"悩ます (なやます)","definition":"làm phiền muộn","example":"この問題が私を悩ませている。","topic":"Verbs N2"},
  {"id":"nf-1094","word":"免れる (まぬかれる)","definition":"thoát khỏi","example":"事故を免れた。","topic":"Verbs N2"},
  {"id":"nf-1095","word":"陥る (おちいる)","definition":"rơi vào (tình trạng xấu)","example":"不況に陥る。","topic":"Verbs N2"},
  {"id":"nf-1096","word":"浸る (ひたる)","definition":"ngâm mình, đắm chìm","example":"温泉に浸る。","topic":"Verbs N2"},
  {"id":"nf-1097","word":"築く (きずく)","definition":"xây dựng","example":"信頼関係を築く。","topic":"Verbs N2"},
  {"id":"nf-1098","word":"抱く (いだく)","definition":"ôm ấp, mang (cảm xúc)","example":"夢を抱いて生きる。","topic":"Verbs N2"},
  {"id":"nf-1099","word":"施す (ほどこす)","definition":"ban cho, thi hành","example":"治療を施す。","topic":"Verbs N2"},
  {"id":"nf-1100","word":"捧げる (ささげる)","definition":"dâng hiến","example":"人生を研究に捧げた。","topic":"Verbs N2"},
  {"id":"nf-1101","word":"諦める (あきらめる)","definition":"từ bỏ","example":"夢を諦めない。","topic":"Verbs N2"},
  {"id":"nf-1102","word":"焦る (あせる)","definition":"nóng vội, sốt ruột","example":"焦っても良いことはない。","topic":"Verbs N2"},
  {"id":"nf-1103","word":"甘える (あまえる)","definition":"nhõng nhẽo, ỷ lại","example":"子供が母親に甘えている。","topic":"Verbs N2"},
  {"id":"nf-1104","word":"嘆く (なげく)","definition":"than thở, kêu ca","example":"世の中の不公平を嘆く。","topic":"Verbs N2"},
  {"id":"nf-1105","word":"励ます (はげます)","definition":"khích lệ, động viên","example":"友人を励ました。","topic":"Verbs N2"},

  # === Expressions & Idioms - 100 cards ===
  {"id":"nf-1106","word":"手を打つ (てをうつ)","definition":"đưa ra biện pháp","example":"問題が大きくなる前に手を打つ。","topic":"Expressions"},
  {"id":"nf-1107","word":"口を出す (くちをだす)","definition":"xen vào, can thiệp","example":"人の仕事に口を出さないでください。","topic":"Expressions"},
  {"id":"nf-1108","word":"目を向ける (めをむける)","definition":"chú ý đến","example":"新しい市場に目を向ける。","topic":"Expressions"},
  {"id":"nf-1109","word":"気を配る (きをくばる)","definition":"quan tâm, để ý","example":"細部にまで気を配る。","topic":"Expressions"},
  {"id":"nf-1110","word":"腕を振るう (うでをふるう)","definition":"phát huy tài năng","example":"料理の腕を振るった。","topic":"Expressions"},
  {"id":"nf-1111","word":"足を引っ張る (あしをひっぱる)","definition":"kéo chân, cản trở","example":"チームの足を引っ張りたくない。","topic":"Expressions"},
  {"id":"nf-1112","word":"頭を抱える (あたまをかかえる)","definition":"ôm đầu, lo lắng","example":"難しい問題に頭を抱えている。","topic":"Expressions"},
  {"id":"nf-1113","word":"胸を打つ (むねをうつ)","definition":"cảm động","example":"彼のスピーチは胸を打った。","topic":"Expressions"},
  {"id":"nf-1114","word":"肩を持つ (かたをもつ)","definition":"bênh vực, ủng hộ","example":"いつも弟の肩を持つ。","topic":"Expressions"},
  {"id":"nf-1115","word":"耳を傾ける (みみをかたむける)","definition":"lắng nghe","example":"先輩の話に耳を傾ける。","topic":"Expressions"},
  {"id":"nf-1116","word":"身につける (みにつける)","definition":"học được, trang bị","example":"新しいスキルを身につける。","topic":"Expressions"},
  {"id":"nf-1117","word":"気に入る (きにいる)","definition":"thích, ưng ý","example":"この店がとても気に入った。","topic":"Expressions"},
  {"id":"nf-1118","word":"気にかける (きにかける)","definition":"quan tâm, bận tâm","example":"部下のことを気にかけている。","topic":"Expressions"},
  {"id":"nf-1119","word":"気が済む (きがすむ)","definition":"thỏa mãn, yên tâm","example":"全部やるまで気が済まない。","topic":"Expressions"},
  {"id":"nf-1120","word":"気が利く (きがきく)","definition":"tinh ý, chu đáo","example":"彼女はとても気が利く人だ。","topic":"Expressions"},
  {"id":"nf-1121","word":"顔が広い (かおがひろい)","definition":"quen biết rộng","example":"彼は業界で顔が広い。","topic":"Expressions"},
  {"id":"nf-1122","word":"腹を立てる (はらをたてる)","definition":"tức giận","example":"理不尽なことに腹を立てた。","topic":"Expressions"},
  {"id":"nf-1123","word":"骨を折る (ほねをおる)","definition":"nỗ lực, vất vả","example":"彼のために骨を折った。","topic":"Expressions"},
  {"id":"nf-1124","word":"目を通す (めをとおす)","definition":"xem qua, đọc lướt","example":"書類に目を通してください。","topic":"Expressions"},
  {"id":"nf-1125","word":"手を抜く (てをぬく)","definition":"làm qua loa, tắt trách","example":"仕事で手を抜いてはいけない。","topic":"Expressions"},
  {"id":"nf-1126","word":"腕が立つ (うでがたつ)","definition":"có tay nghề cao","example":"彼は料理の腕が立つ。","topic":"Expressions"},
  {"id":"nf-1127","word":"首を突っ込む (くびをつっこむ)","definition":"xen vào, tọc mạch","example":"他人の問題に首を突っ込まない。","topic":"Expressions"},
  {"id":"nf-1128","word":"息を呑む (いきをのむ)","definition":"nín thở (kinh ngạc)","example":"息を呑むような美しい景色。","topic":"Expressions"},
  {"id":"nf-1129","word":"一石二鳥 (いっせきにちょう)","definition":"một mũi tên trúng hai đích","example":"運動と通勤を兼ねて一石二鳥だ。","topic":"Expressions"},
  {"id":"nf-1130","word":"以心伝心 (いしんでんしん)","definition":"tâm truyền tâm","example":"長年の夫婦は以心伝心だ。","topic":"Expressions"},
  {"id":"nf-1131","word":"七転び八起き (ななころびやおき)","definition":"bảy lần ngã, tám lần đứng dậy","example":"七転び八起きの精神で頑張る。","topic":"Expressions"},
  {"id":"nf-1132","word":"十人十色 (じゅうにんといろ)","definition":"mười người mười vẻ","example":"考え方は十人十色だ。","topic":"Expressions"},
  {"id":"nf-1133","word":"油断大敵 (ゆだんたいてき)","definition":"chủ quan là kẻ thù lớn","example":"油断大敵、気を引き締めよう。","topic":"Expressions"},
  {"id":"nf-1134","word":"自業自得 (じごうじとく)","definition":"tự làm tự chịu","example":"遅刻して怒られるのは自業自得だ。","topic":"Expressions"},
  {"id":"nf-1135","word":"試行錯誤 (しこうさくご)","definition":"thử và sai","example":"試行錯誤を繰り返して完成させた。","topic":"Expressions"},
  {"id":"nf-1136","word":"前代未聞 (ぜんだいみもん)","definition":"chưa từng có","example":"前代未聞の大事件が起きた。","topic":"Expressions"},
  {"id":"nf-1137","word":"一長一短 (いっちょういったん)","definition":"có hay có dở","example":"どの方法も一長一短がある。","topic":"Expressions"},
  {"id":"nf-1138","word":"臨機応変 (りんきおうへん)","definition":"linh hoạt tùy cơ ứng biến","example":"臨機応変に対応する。","topic":"Expressions"},
  {"id":"nf-1139","word":"言語道断 (ごんごどうだん)","definition":"không thể tha thứ","example":"そんな行為は言語道断だ。","topic":"Expressions"},
  {"id":"nf-1140","word":"紆余曲折 (うよきょくせつ)","definition":"quanh co, trắc trở","example":"紆余曲折を経て成功した。","topic":"Expressions"},
  {"id":"nf-1141","word":"付き合い (つきあい)","definition":"giao tiếp, quan hệ xã hội","example":"近所付き合いが大切だ。","topic":"Expressions"},
  {"id":"nf-1142","word":"腕前 (うでまえ)","definition":"tay nghề, kỹ năng","example":"彼の腕前は相当なものだ。","topic":"Expressions"},
  {"id":"nf-1143","word":"見通し (みとおし)","definition":"triển vọng, dự báo","example":"景気回復の見通しは明るい。","topic":"Expressions"},
  {"id":"nf-1144","word":"歯止め (はどめ)","definition":"phanh hãm, giới hạn","example":"物価の上昇に歯止めをかける。","topic":"Expressions"},
  {"id":"nf-1145","word":"手がかり (てがかり)","definition":"manh mối, đầu mối","example":"犯人の手がかりを見つけた。","topic":"Expressions"},
  {"id":"nf-1146","word":"きっかけ","definition":"cơ hội, khởi đầu","example":"日本語を勉強するきっかけはアニメだった。","topic":"Expressions"},
  {"id":"nf-1147","word":"やりがい","definition":"giá trị, đáng làm","example":"やりがいのある仕事。","topic":"Expressions"},
  {"id":"nf-1148","word":"生きがい (いきがい)","definition":"lẽ sống, niềm vui sống","example":"趣味が生きがいになっている。","topic":"Expressions"},
  {"id":"nf-1149","word":"甲斐 (かい)","definition":"giá trị, đáng (nỗ lực)","example":"努力した甲斐があった。","topic":"Expressions"},
  {"id":"nf-1150","word":"心当たり (こころあたり)","definition":"manh mối, nghi ngờ","example":"心当たりはありますか。","topic":"Expressions"},
  {"id":"nf-1151","word":"見当 (けんとう)","definition":"ước chừng, phỏng đoán","example":"見当もつかない。","topic":"Expressions"},
  {"id":"nf-1152","word":"筋 (すじ)","definition":"đạo lý, hợp lý","example":"筋の通った意見だ。","topic":"Expressions"},
  {"id":"nf-1153","word":"一目瞭然 (いちもくりょうぜん)","definition":"rõ ràng ngay từ cái nhìn đầu","example":"グラフを見れば一目瞭然だ。","topic":"Expressions"},
  {"id":"nf-1154","word":"四苦八苦 (しくはっく)","definition":"vất vả, khổ sở","example":"締め切りに追われて四苦八苦している。","topic":"Expressions"},
  {"id":"nf-1155","word":"無我夢中 (むがむちゅう)","definition":"mải mê, quên mình","example":"無我夢中で走った。","topic":"Expressions"},
  {"id":"nf-1156","word":"二の足を踏む (にのあしをふむ)","definition":"do dự, chần chừ","example":"高い買い物に二の足を踏んだ。","topic":"Expressions"},
  {"id":"nf-1157","word":"釘を刺す (くぎをさす)","definition":"nhắc nhở, cảnh báo trước","example":"遅刻しないよう釘を刺した。","topic":"Expressions"},
  {"id":"nf-1158","word":"水を差す (みずをさす)","definition":"xen vào, phá đám","example":"楽しい雰囲気に水を差す発言。","topic":"Expressions"},
  {"id":"nf-1159","word":"図に乗る (ずにのる)","definition":"tự mãn, làm quá","example":"褒められて図に乗っている。","topic":"Expressions"},
  {"id":"nf-1160","word":"拍車をかける (はくしゃをかける)","definition":"thúc đẩy, làm tăng tốc","example":"技術革新が経済成長に拍車をかけた。","topic":"Expressions"},
  {"id":"nf-1161","word":"的を射る (まとをいる)","definition":"nói trúng, chính xác","example":"彼の指摘は的を射ている。","topic":"Expressions"},
  {"id":"nf-1162","word":"角を立てる (かどをたてる)","definition":"gây xích mích","example":"角を立てないように話す。","topic":"Expressions"},
  {"id":"nf-1163","word":"虫がいい (むしがいい)","definition":"ích kỷ, đòi hỏi quá","example":"それは少し虫がいい話だ。","topic":"Expressions"},
  {"id":"nf-1164","word":"場をわきまえる","definition":"biết phân biệt tình huống","example":"場をわきまえた行動をする。","topic":"Expressions"},
  {"id":"nf-1165","word":"白紙に戻す (はくしにもどす)","definition":"trở về con số 0, hủy bỏ","example":"計画を白紙に戻す。","topic":"Expressions"},
  {"id":"nf-1166","word":"一から出直す (いちからでなおす)","definition":"làm lại từ đầu","example":"失敗したので一から出直す。","topic":"Expressions"},
  {"id":"nf-1167","word":"痒い所に手が届く (かゆいところにてがとどく)","definition":"chu đáo tận tình","example":"痒い所に手が届くサービス。","topic":"Expressions"},
  {"id":"nf-1168","word":"雲をつかむ (くもをつかむ)","definition":"mơ hồ, không rõ ràng","example":"雲をつかむような話だ。","topic":"Expressions"},
  {"id":"nf-1169","word":"袋小路 (ふくろこうじ)","definition":"ngõ cụt, bế tắc","example":"交渉は袋小路に入った。","topic":"Expressions"},
  {"id":"nf-1170","word":"根も葉もない (ねもはもない)","definition":"không căn cứ, vô căn cứ","example":"根も葉もない噂を流す。","topic":"Expressions"},
  {"id":"nf-1171","word":"棚に上げる (たなにあげる)","definition":"gác sang một bên","example":"自分のことは棚に上げて人を批判する。","topic":"Expressions"},
  {"id":"nf-1172","word":"目の当たりにする (まのあたりにする)","definition":"chứng kiến tận mắt","example":"災害の被害を目の当たりにした。","topic":"Expressions"},
  {"id":"nf-1173","word":"身を粉にする (みをこにする)","definition":"làm việc quên mình","example":"家族のために身を粉にして働いた。","topic":"Expressions"},
  {"id":"nf-1174","word":"手に余る (てにあまる)","definition":"quá sức, không thể xử lý","example":"この問題は私の手に余る。","topic":"Expressions"},
  {"id":"nf-1175","word":"腰を据える (こしをすえる)","definition":"kiên nhẫn, ổn định","example":"腰を据えて取り組む。","topic":"Expressions"},
  {"id":"nf-1176","word":"堂々と (どうどうと)","definition":"đàng hoàng, oai vệ","example":"堂々と意見を述べた。","topic":"Expressions"},
  {"id":"nf-1177","word":"やむを得ない","definition":"bất đắc dĩ, không thể tránh","example":"やむを得ない事情で欠席した。","topic":"Expressions"},
  {"id":"nf-1178","word":"ありがちな","definition":"thường gặp, hay xảy ra","example":"初心者にありがちなミス。","topic":"Expressions"},
  {"id":"nf-1179","word":"一目置く (いちもくおく)","definition":"nể phục","example":"彼の能力には一目置いている。","topic":"Expressions"},
  {"id":"nf-1180","word":"馬が合う (うまがあう)","definition":"hợp nhau, ăn ý","example":"彼女とは馬が合う。","topic":"Expressions"},
  {"id":"nf-1181","word":"後を絶たない (あとをたたない)","definition":"không ngừng, liên tiếp","example":"交通事故が後を絶たない。","topic":"Expressions"},
  {"id":"nf-1182","word":"顔を立てる (かおをたてる)","definition":"giữ thể diện cho ai","example":"上司の顔を立てる。","topic":"Expressions"},
  {"id":"nf-1183","word":"釘付けになる (くぎづけになる)","definition":"bị thu hút, dán mắt","example":"テレビに釘付けになった。","topic":"Expressions"},
  {"id":"nf-1184","word":"腹を割って (はらをわって)","definition":"thành thật, bộc bạch","example":"腹を割って話し合おう。","topic":"Expressions"},
  {"id":"nf-1185","word":"花を持たせる (はなをもたせる)","definition":"nhường phần thắng cho ai","example":"後輩に花を持たせた。","topic":"Expressions"},
  {"id":"nf-1186","word":"身を引く (みをひく)","definition":"rút lui, từ bỏ","example":"競争から身を引いた。","topic":"Expressions"},
  {"id":"nf-1187","word":"手を尽くす (てをつくす)","definition":"tận lực, cố hết sức","example":"手を尽くしたが間に合わなかった。","topic":"Expressions"},
  {"id":"nf-1188","word":"根を詰める (ねをつめる)","definition":"miệt mài, lao vào","example":"根を詰めて勉強した。","topic":"Expressions"},
  {"id":"nf-1189","word":"板挟み (いたばさみ)","definition":"bị kẹt giữa, tiến thoái lưỡng nan","example":"上司と部下の板挟みになる。","topic":"Expressions"},
  {"id":"nf-1190","word":"思いがけない (おもいがけない)","definition":"bất ngờ, ngoài dự kiến","example":"思いがけない出来事が起きた。","topic":"Expressions"},
  {"id":"nf-1191","word":"口が堅い (くちがかたい)","definition":"kín miệng, giữ bí mật","example":"彼は口が堅いので安心だ。","topic":"Expressions"},
  {"id":"nf-1192","word":"口が軽い (くちがかるい)","definition":"lỡ miệng, hay nói","example":"口が軽い人には秘密を言えない。","topic":"Expressions"},
  {"id":"nf-1193","word":"肝に銘じる (きもにめいじる)","definition":"khắc cốt ghi tâm","example":"先生の言葉を肝に銘じる。","topic":"Expressions"},
  {"id":"nf-1194","word":"念を押す (ねんをおす)","definition":"nhắc lại, xác nhận kỹ","example":"出発前に念を押した。","topic":"Expressions"},
  {"id":"nf-1195","word":"有無を言わさず (うむをいわさず)","definition":"không cho phép từ chối","example":"有無を言わさず参加させられた。","topic":"Expressions"},
  {"id":"nf-1196","word":"目に余る (めにあまる)","definition":"quá đáng, không thể chấp nhận","example":"彼の態度は目に余る。","topic":"Expressions"},
  {"id":"nf-1197","word":"横槍を入れる (よこやりをいれる)","definition":"xen ngang, gây trở ngại","example":"横槍を入れないでください。","topic":"Expressions"},
  {"id":"nf-1198","word":"理に適う (りにかなう)","definition":"hợp lý, có lý","example":"彼の主張は理に適っている。","topic":"Expressions"},
  {"id":"nf-1199","word":"鶴の一声 (つるのひとこえ)","definition":"một tiếng nói quyết định","example":"社長の鶴の一声で決まった。","topic":"Expressions"},
  {"id":"nf-1200","word":"猫の手も借りたい (ねこのてもかりたい)","definition":"bận rộn cực kỳ","example":"年末は猫の手も借りたいほど忙しい。","topic":"Expressions"},
  {"id":"nf-1201","word":"蛇足 (だそく)","definition":"thừa, vẽ rắn thêm chân","example":"蛇足かもしれませんが一言。","topic":"Expressions"},
  {"id":"nf-1202","word":"玉石混交 (ぎょくせきこんこう)","definition":"vàng thau lẫn lộn","example":"ネットの情報は玉石混交だ。","topic":"Expressions"},
  {"id":"nf-1203","word":"切磋琢磨 (せっさたくま)","definition":"tôi luyện, trau dồi","example":"仲間と切磋琢磨して成長する。","topic":"Expressions"},
  {"id":"nf-1204","word":"先見の明 (せんけんのめい)","definition":"tầm nhìn xa","example":"彼には先見の明がある。","topic":"Expressions"},
  {"id":"nf-1205","word":"本末転倒 (ほんまつてんとう)","definition":"đảo lộn chính phụ","example":"手段が目的になるのは本末転倒だ。","topic":"Expressions"},

  # === Reading/Formal - 100 cards ===
  {"id":"nf-1206","word":"あらゆる","definition":"mọi, tất cả","example":"あらゆる手段を講じる。","topic":"Formal"},
  {"id":"nf-1207","word":"いかなる","definition":"bất kỳ, dù thế nào","example":"いかなる理由があっても許されない。","topic":"Formal"},
  {"id":"nf-1208","word":"著しく (いちじるしく)","definition":"một cách rõ rệt","example":"成績が著しく向上した。","topic":"Formal"},
  {"id":"nf-1209","word":"直ちに (ただちに)","definition":"ngay lập tức","example":"直ちに対応してください。","topic":"Formal"},
  {"id":"nf-1210","word":"速やかに (すみやかに)","definition":"nhanh chóng","example":"速やかに避難してください。","topic":"Formal"},
  {"id":"nf-1211","word":"概して (がいして)","definition":"nhìn chung","example":"概して結果は良好だった。","topic":"Formal"},
  {"id":"nf-1212","word":"総じて (そうじて)","definition":"nói chung","example":"総じて今年の業績は好調だ。","topic":"Formal"},
  {"id":"nf-1213","word":"従って (したがって)","definition":"do đó, theo đó","example":"予算が足りない。従って計画を見直す。","topic":"Formal"},
  {"id":"nf-1214","word":"即ち (すなわち)","definition":"tức là","example":"彼は社長、即ち最高責任者だ。","topic":"Formal"},
  {"id":"nf-1215","word":"且つ (かつ)","definition":"và, đồng thời","example":"安全且つ効率的な方法。","topic":"Formal"},
  {"id":"nf-1216","word":"尚 (なお)","definition":"hơn nữa, ngoài ra","example":"尚、詳細は後日連絡いたします。","topic":"Formal"},
  {"id":"nf-1217","word":"及び (および)","definition":"và, cùng với","example":"社長及び副社長が出席した。","topic":"Formal"},
  {"id":"nf-1218","word":"或いは (あるいは)","definition":"hoặc là","example":"電話、或いはメールでご連絡ください。","topic":"Formal"},
  {"id":"nf-1219","word":"若しくは (もしくは)","definition":"hoặc là (pháp luật)","example":"本人若しくは代理人が申請する。","topic":"Formal"},
  {"id":"nf-1220","word":"但し (ただし)","definition":"tuy nhiên, nhưng","example":"参加は無料。但し、事前登録が必要です。","topic":"Formal"},
  {"id":"nf-1221","word":"一方 (いっぽう)","definition":"một mặt, trong khi đó","example":"輸出は増加した。一方、輸入は減少した。","topic":"Formal"},
  {"id":"nf-1222","word":"もっとも","definition":"tuy nhiên, dĩ nhiên","example":"賛成だ。もっとも条件がある。","topic":"Formal"},
  {"id":"nf-1223","word":"要するに (ようするに)","definition":"tóm lại, nói tóm lại","example":"要するに、予算が足りない。","topic":"Formal"},
  {"id":"nf-1224","word":"言わば (いわば)","definition":"có thể nói là","example":"彼は言わばチームの柱だ。","topic":"Formal"},
  {"id":"nf-1225","word":"ひいては","definition":"và rồi, từ đó dẫn đến","example":"個人の努力が、ひいては社会全体の発展につながる。","topic":"Formal"},
  {"id":"nf-1226","word":"とりわけ","definition":"đặc biệt, nhất là","example":"日本の文化、とりわけ茶道に興味がある。","topic":"Formal"},
  {"id":"nf-1227","word":"ことに","definition":"đặc biệt là","example":"今年はことに暑い夏だった。","topic":"Formal"},
  {"id":"nf-1228","word":"殊に (ことに)","definition":"đặc biệt là (văn viết)","example":"殊に注意すべき点がある。","topic":"Formal"},
  {"id":"nf-1229","word":"辛うじて (かろうじて)","definition":"một cách vất vả, chỉ vừa đủ","example":"辛うじて試験に合格した。","topic":"Formal"},
  {"id":"nf-1230","word":"敢えて (あえて)","definition":"dám, cố tình","example":"敢えて反対意見を述べる。","topic":"Formal"},
  {"id":"nf-1231","word":"至急 (しきゅう)","definition":"khẩn cấp","example":"至急ご連絡ください。","topic":"Formal"},
  {"id":"nf-1232","word":"早急 (さっきゅう)","definition":"khẩn trương, gấp rút","example":"早急に対応する必要がある。","topic":"Formal"},
  {"id":"nf-1233","word":"多少 (たしょう)","definition":"ít nhiều, đôi chút","example":"多少の遅れは仕方がない。","topic":"Formal"},
  {"id":"nf-1234","word":"大幅 (おおはば)","definition":"đáng kể, lớn","example":"大幅な値引きを行う。","topic":"Formal"},
  {"id":"nf-1235","word":"若干 (じゃっかん)","definition":"một ít, chút ít","example":"若干の修正が必要だ。","topic":"Formal"},
  {"id":"nf-1236","word":"相当 (そうとう)","definition":"tương đối, khá","example":"相当な努力が必要だ。","topic":"Formal"},
  {"id":"nf-1237","word":"一層 (いっそう)","definition":"hơn nữa, càng","example":"一層の努力が求められる。","topic":"Formal"},
  {"id":"nf-1238","word":"一斉に (いっせいに)","definition":"đồng loạt","example":"一斉に拍手が起きた。","topic":"Formal"},
  {"id":"nf-1239","word":"一旦 (いったん)","definition":"một khi, tạm thời","example":"一旦決めたら変更しない。","topic":"Formal"},
  {"id":"nf-1240","word":"一連の (いちれんの)","definition":"một loạt","example":"一連の事件を調査する。","topic":"Formal"},
  {"id":"nf-1241","word":"日頃 (ひごろ)","definition":"hàng ngày, thường ngày","example":"日頃の努力が実を結んだ。","topic":"Formal"},
  {"id":"nf-1242","word":"常に (つねに)","definition":"luôn luôn","example":"常に最善を尽くす。","topic":"Formal"},
  {"id":"nf-1243","word":"絶えず (たえず)","definition":"không ngừng","example":"技術は絶えず進歩している。","topic":"Formal"},
  {"id":"nf-1244","word":"間もなく (まもなく)","definition":"sắp, không lâu nữa","example":"間もなく電車が到着します。","topic":"Formal"},
  {"id":"nf-1245","word":"かねてから","definition":"từ lâu, từ trước","example":"かねてから計画していた旅行。","topic":"Formal"},
  {"id":"nf-1246","word":"漸く (ようやく)","definition":"cuối cùng, rốt cuộc","example":"漸く目標を達成した。","topic":"Formal"},
  {"id":"nf-1247","word":"案外 (あんがい)","definition":"bất ngờ, ngoài dự kiến","example":"案外簡単だった。","topic":"Formal"},
  {"id":"nf-1248","word":"意外 (いがい)","definition":"bất ngờ, ngoài sự mong đợi","example":"意外な結果に驚いた。","topic":"Formal"},
  {"id":"nf-1249","word":"存外 (ぞんがい)","definition":"hơn dự tưởng","example":"存外早く終わった。","topic":"Formal"},
  {"id":"nf-1250","word":"生憎 (あいにく)","definition":"không may, đáng tiếc","example":"生憎、本日は定休日です。","topic":"Formal"},
  {"id":"nf-1251","word":"折角 (せっかく)","definition":"khó khăn lắm mới","example":"折角のチャンスを逃した。","topic":"Formal"},
  {"id":"nf-1252","word":"案の定 (あんのじょう)","definition":"quả đúng như dự đoán","example":"案の定、雨が降り出した。","topic":"Formal"},
  {"id":"nf-1253","word":"挙げて (あげて)","definition":"tổng động viên","example":"全社を挙げて取り組む。","topic":"Formal"},
  {"id":"nf-1254","word":"掛け替えのない (かけがえのない)","definition":"không thể thay thế","example":"掛け替えのない友人。","topic":"Formal"},
  {"id":"nf-1255","word":"心得る (こころえる)","definition":"hiểu rõ, nắm được","example":"礼儀を心得ている人。","topic":"Formal"},

  # === Culture & Society - 100 cards ===
  {"id":"nf-1256","word":"風習 (ふうしゅう)","definition":"phong tục","example":"地域の風習を大切にする。","topic":"Culture"},
  {"id":"nf-1257","word":"伝統 (でんとう)","definition":"truyền thống","example":"伝統を守りながら革新する。","topic":"Culture"},
  {"id":"nf-1258","word":"習慣 (しゅうかん)","definition":"thói quen, tập quán","example":"早起きの習慣をつける。","topic":"Culture"},
  {"id":"nf-1259","word":"風潮 (ふうちょう)","definition":"xu hướng, trào lưu","example":"最近の社会的風潮。","topic":"Culture"},
  {"id":"nf-1260","word":"世代 (せだい)","definition":"thế hệ","example":"世代間の価値観の違い。","topic":"Culture"},
  {"id":"nf-1261","word":"模範 (もはん)","definition":"mẫu mực, tấm gương","example":"模範的な行動をとる。","topic":"Culture"},
  {"id":"nf-1262","word":"道徳 (どうとく)","definition":"đạo đức","example":"道徳心を育てる。","topic":"Culture"},
  {"id":"nf-1263","word":"倫理 (りんり)","definition":"luân lý, đạo đức (học thuật)","example":"医療倫理について議論する。","topic":"Culture"},
  {"id":"nf-1264","word":"礼儀 (れいぎ)","definition":"lễ nghi, phép lịch sự","example":"礼儀正しい人だ。","topic":"Culture"},
  {"id":"nf-1265","word":"風情 (ふぜい)","definition":"phong tình, tình thú","example":"京都の風情を楽しむ。","topic":"Culture"},
  {"id":"nf-1266","word":"趣 (おもむき)","definition":"vẻ đẹp, phong vị","example":"日本庭園の趣がある。","topic":"Culture"},
  {"id":"nf-1267","word":"美意識 (びいしき)","definition":"ý thức về cái đẹp","example":"日本人特有の美意識。","topic":"Culture"},
  {"id":"nf-1268","word":"郷土 (きょうど)","definition":"quê hương","example":"郷土料理を味わう。","topic":"Culture"},
  {"id":"nf-1269","word":"祭り (まつり)","definition":"lễ hội","example":"夏祭りに参加する。","topic":"Culture"},
  {"id":"nf-1270","word":"神社 (じんじゃ)","definition":"đền thờ (Shinto)","example":"初詣で神社に行く。","topic":"Culture"},
  {"id":"nf-1271","word":"寺院 (じいん)","definition":"chùa (Buddhism)","example":"京都の有名な寺院を訪れた。","topic":"Culture"},
  {"id":"nf-1272","word":"参拝 (さんぱい)","definition":"viếng thăm (đền/chùa)","example":"神社に参拝する。","topic":"Culture"},
  {"id":"nf-1273","word":"書道 (しょどう)","definition":"thư pháp","example":"書道を習っている。","topic":"Culture"},
  {"id":"nf-1274","word":"華道 (かどう)","definition":"cắm hoa (ikebana)","example":"華道の展覧会を見に行く。","topic":"Culture"},
  {"id":"nf-1275","word":"茶道 (さどう)","definition":"trà đạo","example":"茶道を通じて日本文化を学ぶ。","topic":"Culture"},
  {"id":"nf-1276","word":"武道 (ぶどう)","definition":"võ đạo","example":"武道を通じて精神を鍛える。","topic":"Culture"},
  {"id":"nf-1277","word":"着物 (きもの)","definition":"kimono, áo truyền thống","example":"成人式で着物を着る。","topic":"Culture"},
  {"id":"nf-1278","word":"浴衣 (ゆかた)","definition":"yukata, áo tắm truyền thống","example":"花火大会に浴衣を着て行く。","topic":"Culture"},
  {"id":"nf-1279","word":"温泉 (おんせん)","definition":"suối nước nóng","example":"週末に温泉に行く。","topic":"Culture"},
  {"id":"nf-1280","word":"旅館 (りょかん)","definition":"nhà trọ truyền thống","example":"温泉旅館に泊まった。","topic":"Culture"},
  {"id":"nf-1281","word":"畳 (たたみ)","definition":"chiếu tatami","example":"畳の部屋で寝る。","topic":"Culture"},
  {"id":"nf-1282","word":"障子 (しょうじ)","definition":"cửa giấy truyền thống","example":"障子を開けて庭を眺める。","topic":"Culture"},
  {"id":"nf-1283","word":"襖 (ふすま)","definition":"cửa lùa (trong nhà)","example":"襖で部屋を仕切る。","topic":"Culture"},
  {"id":"nf-1284","word":"地域社会 (ちいきしゃかい)","definition":"cộng đồng địa phương","example":"地域社会に貢献する。","topic":"Culture"},
  {"id":"nf-1285","word":"世間 (せけん)","definition":"thế gian, xã hội","example":"世間の目を気にする。","topic":"Culture"},
  {"id":"nf-1286","word":"気質 (きしつ)","definition":"khí chất, tính cách","example":"関西人の気質は明るい。","topic":"Culture"},
  {"id":"nf-1287","word":"人情 (にんじょう)","definition":"tình người","example":"人情味のある町だ。","topic":"Culture"},
  {"id":"nf-1288","word":"義理 (ぎり)","definition":"nghĩa vụ, bổn phận","example":"義理を果たす。","topic":"Culture"},
  {"id":"nf-1289","word":"恩 (おん)","definition":"ơn, ân","example":"恩を返す。","topic":"Culture"},
  {"id":"nf-1290","word":"思いやり (おもいやり)","definition":"sự quan tâm, lòng nhân ái","example":"思いやりのある人になりたい。","topic":"Culture"},
  {"id":"nf-1291","word":"謙虚 (けんきょ)","definition":"khiêm tốn","example":"謙虚な態度で学ぶ。","topic":"Culture"},
  {"id":"nf-1292","word":"誠実 (せいじつ)","definition":"thành thật, trung thực","example":"誠実に対応する。","topic":"Culture"},
  {"id":"nf-1293","word":"勤勉 (きんべん)","definition":"cần mẫn, siêng năng","example":"勤勉な学生だ。","topic":"Culture"},
  {"id":"nf-1294","word":"忍耐 (にんたい)","definition":"nhẫn nại, chịu đựng","example":"忍耐力を養う。","topic":"Culture"},
  {"id":"nf-1295","word":"根気 (こんき)","definition":"kiên nhẫn, bền bỉ","example":"根気よく続けることが大事だ。","topic":"Culture"},
  {"id":"nf-1296","word":"志望 (しぼう)","definition":"chí nguyện, nguyện vọng","example":"医学部を志望している。","topic":"Culture"},
  {"id":"nf-1297","word":"抱負 (ほうふ)","definition":"hoài bão, quyết tâm","example":"新年の抱負を語る。","topic":"Culture"},
  {"id":"nf-1298","word":"人脈 (じんみゃく)","definition":"mạng lưới quan hệ","example":"広い人脈を持っている。","topic":"Culture"},
  {"id":"nf-1299","word":"出世 (しゅっせ)","definition":"thăng tiến, thành đạt","example":"彼は順調に出世している。","topic":"Culture"},
  {"id":"nf-1300","word":"転職 (てんしょく)","definition":"chuyển việc","example":"転職を考えている。","topic":"Culture"},
  {"id":"nf-1301","word":"定年 (ていねん)","definition":"tuổi nghỉ hưu","example":"来年定年を迎える。","topic":"Culture"},
  {"id":"nf-1302","word":"共働き (ともばたらき)","definition":"vợ chồng cùng đi làm","example":"共働きの家庭が増えている。","topic":"Culture"},
  {"id":"nf-1303","word":"育児 (いくじ)","definition":"nuôi con","example":"育児と仕事の両立は大変だ。","topic":"Culture"},
  {"id":"nf-1304","word":"介護 (かいご)","definition":"chăm sóc người già/bệnh","example":"親の介護をしている。","topic":"Culture"},
  {"id":"nf-1305","word":"相続 (そうぞく)","definition":"thừa kế","example":"財産を相続する。","topic":"Culture"},

  # === Technology & Modern - 50 cards ===
  {"id":"nf-1306","word":"人工知能 (じんこうちのう)","definition":"trí tuệ nhân tạo (AI)","example":"人工知能が急速に発展している。","topic":"Technology"},
  {"id":"nf-1307","word":"自動化 (じどうか)","definition":"tự động hóa","example":"工場の自動化が進んでいる。","topic":"Technology"},
  {"id":"nf-1308","word":"革新 (かくしん)","definition":"cách tân, đổi mới","example":"技術革新が社会を変える。","topic":"Technology"},
  {"id":"nf-1309","word":"普及率 (ふきゅうりつ)","definition":"tỷ lệ phổ cập","example":"スマホの普及率は90%を超えた。","topic":"Technology"},
  {"id":"nf-1310","word":"端末 (たんまつ)","definition":"thiết bị đầu cuối","example":"モバイル端末の利用が増加。","topic":"Technology"},
  {"id":"nf-1311","word":"通信 (つうしん)","definition":"thông tin, truyền thông","example":"通信技術が進歩した。","topic":"Technology"},
  {"id":"nf-1312","word":"暗号 (あんごう)","definition":"mật mã","example":"データを暗号化する。","topic":"Technology"},
  {"id":"nf-1313","word":"漏洩 (ろうえい)","definition":"rò rỉ","example":"個人情報が漏洩した。","topic":"Technology"},
  {"id":"nf-1314","word":"更新 (こうしん)","definition":"cập nhật","example":"ソフトウェアを更新する。","topic":"Technology"},
  {"id":"nf-1315","word":"復元 (ふくげん)","definition":"khôi phục","example":"データを復元する。","topic":"Technology"},
  {"id":"nf-1316","word":"接続 (せつぞく)","definition":"kết nối","example":"インターネットに接続する。","topic":"Technology"},
  {"id":"nf-1317","word":"遠隔 (えんかく)","definition":"từ xa","example":"遠隔操作でロボットを動かす。","topic":"Technology"},
  {"id":"nf-1318","word":"仮想 (かそう)","definition":"ảo, giả lập","example":"仮想現実の世界を体験する。","topic":"Technology"},
  {"id":"nf-1319","word":"画期的 (かっきてき)","definition":"đột phá, mang tính bước ngoặt","example":"画期的な発明が生まれた。","topic":"Technology"},
  {"id":"nf-1320","word":"先端 (せんたん)","definition":"tiên tiến, mũi nhọn","example":"最先端の技術を開発する。","topic":"Technology"},
  {"id":"nf-1321","word":"精密 (せいみつ)","definition":"chính xác, tinh vi","example":"精密な機械を製造する。","topic":"Technology"},
  {"id":"nf-1322","word":"高性能 (こうせいのう)","definition":"hiệu suất cao","example":"高性能なコンピューターを導入した。","topic":"Technology"},
  {"id":"nf-1323","word":"需要 (じゅよう)","definition":"nhu cầu","example":"新製品の需要が高まっている。","topic":"Technology"},
  {"id":"nf-1324","word":"供給 (きょうきゅう)","definition":"cung cấp","example":"電力の安定供給を確保する。","topic":"Technology"},
  {"id":"nf-1325","word":"動向 (どうこう)","definition":"xu hướng, diễn biến","example":"市場の動向を注視する。","topic":"Technology"},
  {"id":"nf-1326","word":"兆候 (ちょうこう)","definition":"dấu hiệu, triệu chứng","example":"景気回復の兆候が見える。","topic":"Technology"},
  {"id":"nf-1327","word":"飛躍 (ひやく)","definition":"nhảy vọt, bước tiến","example":"技術の飛躍的な進歩。","topic":"Technology"},
  {"id":"nf-1328","word":"蓄積 (ちくせき)","definition":"tích lũy","example":"知識を蓄積する。","topic":"Technology"},
  {"id":"nf-1329","word":"応用 (おうよう)","definition":"ứng dụng","example":"理論を応用する。","topic":"Technology"},
  {"id":"nf-1330","word":"基盤 (きばん)","definition":"nền tảng, cơ sở","example":"経済の基盤を強化する。","topic":"Technology"},
  {"id":"nf-1331","word":"枠組み (わくぐみ)","definition":"khung, khuôn khổ","example":"新しい枠組みを構築する。","topic":"Technology"},
  {"id":"nf-1332","word":"整備 (せいび)","definition":"trang bị, xây dựng","example":"インフラを整備する。","topic":"Technology"},
  {"id":"nf-1333","word":"耐久性 (たいきゅうせい)","definition":"độ bền","example":"耐久性に優れた素材。","topic":"Technology"},
  {"id":"nf-1334","word":"劣化 (れっか)","definition":"xuống cấp, giảm chất lượng","example":"時間とともに劣化する。","topic":"Technology"},
  {"id":"nf-1335","word":"最適化 (さいてきか)","definition":"tối ưu hóa","example":"システムを最適化する。","topic":"Technology"},
  {"id":"nf-1336","word":"標準化 (ひょうじゅんか)","definition":"chuẩn hóa","example":"作業手順を標準化する。","topic":"Technology"},
  {"id":"nf-1337","word":"多様化 (たようか)","definition":"đa dạng hóa","example":"ニーズが多様化している。","topic":"Technology"},
  {"id":"nf-1338","word":"簡素化 (かんそか)","definition":"đơn giản hóa","example":"手続きを簡素化する。","topic":"Technology"},
  {"id":"nf-1339","word":"合理化 (ごうりか)","definition":"hợp lý hóa","example":"業務の合理化を図る。","topic":"Technology"},
  {"id":"nf-1340","word":"活性化 (かっせいか)","definition":"kích hoạt, làm sôi động","example":"地域経済の活性化を目指す。","topic":"Technology"},
  {"id":"nf-1341","word":"透明性 (とうめいせい)","definition":"tính minh bạch","example":"経営の透明性を確保する。","topic":"Technology"},
  {"id":"nf-1342","word":"柔軟性 (じゅうなんせい)","definition":"tính linh hoạt","example":"柔軟性のある対応が求められる。","topic":"Technology"},
  {"id":"nf-1343","word":"互換性 (ごかんせい)","definition":"tính tương thích","example":"新旧システムの互換性を確認する。","topic":"Technology"},
  {"id":"nf-1344","word":"信頼性 (しんらいせい)","definition":"độ tin cậy","example":"製品の信頼性を高める。","topic":"Technology"},
  {"id":"nf-1345","word":"効率性 (こうりつせい)","definition":"tính hiệu quả","example":"業務の効率性を向上させる。","topic":"Technology"},
  {"id":"nf-1346","word":"生産性 (せいさんせい)","definition":"năng suất","example":"生産性を高める方法を考える。","topic":"Technology"},
  {"id":"nf-1347","word":"収益性 (しゅうえきせい)","definition":"khả năng sinh lời","example":"事業の収益性を分析する。","topic":"Technology"},
  {"id":"nf-1348","word":"将来性 (しょうらいせい)","definition":"triển vọng tương lai","example":"将来性のある分野に投資する。","topic":"Technology"},
  {"id":"nf-1349","word":"利便性 (りべんせい)","definition":"tính tiện lợi","example":"利便性が向上した。","topic":"Technology"},
  {"id":"nf-1350","word":"安全性 (あんぜんせい)","definition":"tính an toàn","example":"食品の安全性を確認する。","topic":"Technology"},
  {"id":"nf-1351","word":"実用性 (じつようせい)","definition":"tính thực dụng","example":"実用性の高い製品。","topic":"Technology"},
  {"id":"nf-1352","word":"汎用性 (はんようせい)","definition":"tính đa năng","example":"汎用性の高い素材。","topic":"Technology"},
  {"id":"nf-1353","word":"即戦力 (そくせんりょく)","definition":"lực lượng tức thì","example":"即戦力になる人材を求めている。","topic":"Technology"},
  {"id":"nf-1354","word":"人材育成 (じんざいいくせい)","definition":"đào tạo nhân lực","example":"人材育成に力を入れている。","topic":"Technology"},
  {"id":"nf-1355","word":"働き方改革 (はたらきかたかいかく)","definition":"cải cách cách làm việc","example":"働き方改革が進められている。","topic":"Technology"},

  # === Connecting/Transition words & Phrases - 150 cards ===
  {"id":"nf-1356","word":"意識 (いしき)","definition":"ý thức","example":"環境に対する意識が高まっている。","topic":"Awareness"},
  {"id":"nf-1357","word":"無意識 (むいしき)","definition":"vô thức","example":"無意識のうちに習慣になった。","topic":"Awareness"},
  {"id":"nf-1358","word":"自覚 (じかく)","definition":"tự giác","example":"責任の自覚を持つ。","topic":"Awareness"},
  {"id":"nf-1359","word":"認識 (にんしき)","definition":"nhận thức","example":"問題の認識を共有する。","topic":"Awareness"},
  {"id":"nf-1360","word":"意識する (いしきする)","definition":"ý thức, để ý","example":"健康を意識した食事。","topic":"Awareness"},
  {"id":"nf-1361","word":"先入観 (せんにゅうかん)","definition":"thành kiến, định kiến","example":"先入観を捨てて考える。","topic":"Awareness"},
  {"id":"nf-1362","word":"固定観念 (こていかんねん)","definition":"quan niệm cố hữu","example":"固定観念にとらわれない。","topic":"Awareness"},
  {"id":"nf-1363","word":"常識 (じょうしき)","definition":"thường thức, hiểu biết phổ thông","example":"常識を疑う。","topic":"Awareness"},
  {"id":"nf-1364","word":"良識 (りょうしき)","definition":"lương tri, phân biệt phải trái","example":"良識ある行動をする。","topic":"Awareness"},
  {"id":"nf-1365","word":"知識 (ちしき)","definition":"kiến thức","example":"幅広い知識を身につける。","topic":"Awareness"},
  {"id":"nf-1366","word":"教養 (きょうよう)","definition":"giáo dưỡng, học vấn","example":"教養のある人だ。","topic":"Awareness"},
  {"id":"nf-1367","word":"素養 (そよう)","definition":"tố chất, nền tảng","example":"音楽の素養がある。","topic":"Awareness"},
  {"id":"nf-1368","word":"見識 (けんしき)","definition":"kiến thức sâu rộng","example":"彼は見識が広い。","topic":"Awareness"},
  {"id":"nf-1369","word":"洞察 (どうさつ)","definition":"sự sáng suốt, hiểu sâu","example":"鋭い洞察力を持っている。","topic":"Awareness"},
  {"id":"nf-1370","word":"直感 (ちょっかん)","definition":"trực giác","example":"直感を信じる。","topic":"Awareness"},
  {"id":"nf-1371","word":"視野 (しや)","definition":"tầm nhìn, tầm mắt","example":"視野を広げる。","topic":"Awareness"},
  {"id":"nf-1372","word":"展望 (てんぼう)","definition":"triển vọng, viễn cảnh","example":"将来の展望を語る。","topic":"Awareness"},
  {"id":"nf-1373","word":"方向性 (ほうこうせい)","definition":"hướng đi, định hướng","example":"会社の方向性を決める。","topic":"Awareness"},
  {"id":"nf-1374","word":"生きる力 (いきるちから)","definition":"năng lực sống","example":"子供たちに生きる力を育む。","topic":"Awareness"},
  {"id":"nf-1375","word":"向上心 (こうじょうしん)","definition":"tinh thần cầu tiến","example":"向上心を持って仕事に取り組む。","topic":"Awareness"},
  {"id":"nf-1376","word":"探究心 (たんきゅうしん)","definition":"tinh thần khám phá","example":"探究心が旺盛な子供。","topic":"Awareness"},
  {"id":"nf-1377","word":"好奇心 (こうきしん)","definition":"tò mò, hiếu kỳ","example":"好奇心が学びの原動力だ。","topic":"Awareness"},
  {"id":"nf-1378","word":"責任感 (せきにんかん)","definition":"tinh thần trách nhiệm","example":"責任感の強い人だ。","topic":"Awareness"},
  {"id":"nf-1379","word":"使命感 (しめいかん)","definition":"sứ mệnh","example":"使命感を持って働く。","topic":"Awareness"},
  {"id":"nf-1380","word":"達成感 (たっせいかん)","definition":"cảm giác đạt được","example":"目標を達成して達成感を味わった。","topic":"Awareness"},
  {"id":"nf-1381","word":"充実感 (じゅうじつかん)","definition":"cảm giác đầy đủ, sung mãn","example":"仕事に充実感を感じる。","topic":"Awareness"},
  {"id":"nf-1382","word":"危機感 (ききかん)","definition":"cảm giác nguy cơ","example":"環境問題に危機感を持つ。","topic":"Awareness"},
  {"id":"nf-1383","word":"連帯感 (れんたいかん)","definition":"tinh thần đoàn kết","example":"チームの連帯感が高まった。","topic":"Awareness"},
  {"id":"nf-1384","word":"疎外感 (そがいかん)","definition":"cảm giác bị xa cách","example":"疎外感を感じている。","topic":"Awareness"},
  {"id":"nf-1385","word":"劣等感 (れっとうかん)","definition":"mặc cảm tự ti","example":"劣等感を克服する。","topic":"Awareness"},
  {"id":"nf-1386","word":"優越感 (ゆうえつかん)","definition":"cảm giác hơn người","example":"優越感に浸る。","topic":"Awareness"},
  {"id":"nf-1387","word":"罪悪感 (ざいあくかん)","definition":"cảm giác tội lỗi","example":"嘘をついて罪悪感を感じた。","topic":"Awareness"},
  {"id":"nf-1388","word":"共感 (きょうかん)","definition":"đồng cảm","example":"彼の考えに共感する。","topic":"Awareness"},
  {"id":"nf-1389","word":"反感 (はんかん)","definition":"ác cảm, phản cảm","example":"彼の態度に反感を持った。","topic":"Awareness"},
  {"id":"nf-1390","word":"同情 (どうじょう)","definition":"đồng tình, thương cảm","example":"被害者に同情する。","topic":"Awareness"},
  {"id":"nf-1391","word":"憧れ (あこがれ)","definition":"sự ngưỡng mộ","example":"パリは私の憧れの都市だ。","topic":"Awareness"},
  {"id":"nf-1392","word":"懐かしい (なつかしい)","definition":"nhớ, bồi hồi","example":"故郷が懐かしい。","topic":"Awareness"},
  {"id":"nf-1393","word":"切ない (せつない)","definition":"đau lòng, buồn xót","example":"別れは切ないものだ。","topic":"Awareness"},
  {"id":"nf-1394","word":"心細い (こころぼそい)","definition":"cô đơn, lo sợ","example":"一人で心細い。","topic":"Awareness"},
  {"id":"nf-1395","word":"心地よい (ここちよい)","definition":"dễ chịu, thoải mái","example":"心地よい風が吹いている。","topic":"Awareness"},
  {"id":"nf-1396","word":"清々しい (すがすがしい)","definition":"trong lành, sảng khoái","example":"清々しい朝の空気。","topic":"Awareness"},
  {"id":"nf-1397","word":"もどかしい","definition":"nóng ruột, sốt ruột","example":"言いたいことが伝わらなくてもどかしい。","topic":"Awareness"},
  {"id":"nf-1398","word":"歯がゆい (はがゆい)","definition":"bực mình vì bất lực","example":"何もできない自分が歯がゆい。","topic":"Awareness"},
  {"id":"nf-1399","word":"頼もしい (たのもしい)","definition":"đáng tin cậy","example":"頼もしい仲間がいて安心だ。","topic":"Awareness"},
  {"id":"nf-1400","word":"際立つ (きわだつ)","definition":"nổi bật","example":"彼の才能は際立っている。","topic":"Awareness"},

  # === Remaining fill to 500 - Mixed Essential N2 ===
  {"id":"nf-1401","word":"粘り強い (ねばりづよい)","definition":"kiên cường, bền bỉ","example":"粘り強く交渉を続けた。","topic":"Mixed N2"},
  {"id":"nf-1402","word":"分かち合う (わかちあう)","definition":"chia sẻ","example":"喜びを分かち合う。","topic":"Mixed N2"},
  {"id":"nf-1403","word":"見守る (みまもる)","definition":"canh giữ, theo dõi","example":"子供の成長を見守る。","topic":"Mixed N2"},
  {"id":"nf-1404","word":"裏付ける (うらづける)","definition":"chứng minh, xác nhận","example":"データが仮説を裏付けた。","topic":"Mixed N2"},
  {"id":"nf-1405","word":"問い直す (といなおす)","definition":"đặt câu hỏi lại","example":"既存の価値観を問い直す。","topic":"Mixed N2"},
  {"id":"nf-1406","word":"差し迫る (さしせまる)","definition":"gấp rút, cận kề","example":"締め切りが差し迫っている。","topic":"Mixed N2"},
  {"id":"nf-1407","word":"意欲 (いよく)","definition":"ý chí, nhiệt huyết","example":"仕事に対する意欲が高い。","topic":"Mixed N2"},
  {"id":"nf-1408","word":"気概 (きがい)","definition":"khí phách","example":"困難に立ち向かう気概がある。","topic":"Mixed N2"},
  {"id":"nf-1409","word":"柱 (はしら)","definition":"cột trụ, trụ cột","example":"彼はチームの柱だ。","topic":"Mixed N2"},
  {"id":"nf-1410","word":"土台 (どだい)","definition":"nền tảng, cơ sở","example":"信頼が人間関係の土台だ。","topic":"Mixed N2"},
  {"id":"nf-1411","word":"浸透 (しんとう)","definition":"thẩm thấu, phổ cập","example":"新しい考え方が社会に浸透した。","topic":"Mixed N2"},
  {"id":"nf-1412","word":"定着 (ていちゃく)","definition":"ổn định, bám rễ","example":"新しい制度が定着した。","topic":"Mixed N2"},
  {"id":"nf-1413","word":"変遷 (へんせん)","definition":"biến đổi, thay đổi","example":"時代の変遷を振り返る。","topic":"Mixed N2"},
  {"id":"nf-1414","word":"推移 (すいい)","definition":"diễn biến, biến chuyển","example":"人口の推移を調べる。","topic":"Mixed N2"},
  {"id":"nf-1415","word":"転換 (てんかん)","definition":"chuyển đổi","example":"政策の転換が求められる。","topic":"Mixed N2"},
  {"id":"nf-1416","word":"革命 (かくめい)","definition":"cách mạng","example":"産業革命が社会を変えた。","topic":"Mixed N2"},
  {"id":"nf-1417","word":"壁 (かべ)","definition":"tường, rào cản","example":"言葉の壁を乗り越える。","topic":"Mixed N2"},
  {"id":"nf-1418","word":"溝 (みぞ)","definition":"rãnh, khoảng cách","example":"世代間の溝を埋める。","topic":"Mixed N2"},
  {"id":"nf-1419","word":"架け橋 (かけはし)","definition":"cầu nối","example":"文化の架け橋になりたい。","topic":"Mixed N2"},
  {"id":"nf-1420","word":"糸口 (いとぐち)","definition":"đầu mối, manh mối","example":"解決の糸口を見つけた。","topic":"Mixed N2"},
  {"id":"nf-1421","word":"突破口 (とっぱこう)","definition":"đột phá khẩu","example":"困難を打開する突破口を探す。","topic":"Mixed N2"},
  {"id":"nf-1422","word":"障壁 (しょうへき)","definition":"rào cản","example":"貿易障壁を撤廃する。","topic":"Mixed N2"},
  {"id":"nf-1423","word":"盲点 (もうてん)","definition":"điểm mù, sơ hở","example":"計画の盲点を突かれた。","topic":"Mixed N2"},
  {"id":"nf-1424","word":"焦点 (しょうてん)","definition":"tiêu điểm","example":"議論の焦点がずれている。","topic":"Mixed N2"},
  {"id":"nf-1425","word":"論点 (ろんてん)","definition":"luận điểm","example":"論点を整理する。","topic":"Mixed N2"},
  {"id":"nf-1426","word":"争点 (そうてん)","definition":"điểm tranh cãi","example":"選挙の争点は経済政策だ。","topic":"Mixed N2"},
  {"id":"nf-1427","word":"妥当性 (だとうせい)","definition":"tính thỏa đáng","example":"判断の妥当性を検証する。","topic":"Mixed N2"},
  {"id":"nf-1428","word":"整合性 (せいごうせい)","definition":"tính nhất quán","example":"データの整合性を確認する。","topic":"Mixed N2"},
  {"id":"nf-1429","word":"一貫性 (いっかんせい)","definition":"tính nhất quán","example":"政策の一貫性が重要だ。","topic":"Mixed N2"},
  {"id":"nf-1430","word":"客観的 (きゃっかんてき)","definition":"khách quan","example":"客観的に事実を分析する。","topic":"Mixed N2"},
  {"id":"nf-1431","word":"主観的 (しゅかんてき)","definition":"chủ quan","example":"主観的な判断を避ける。","topic":"Mixed N2"},
  {"id":"nf-1432","word":"合理的 (ごうりてき)","definition":"hợp lý","example":"合理的な判断を下す。","topic":"Mixed N2"},
  {"id":"nf-1433","word":"効果的 (こうかてき)","definition":"hiệu quả","example":"効果的な学習方法を見つける。","topic":"Mixed N2"},
  {"id":"nf-1434","word":"積極的 (せっきょくてき)","definition":"tích cực","example":"積極的に参加する。","topic":"Mixed N2"},
  {"id":"nf-1435","word":"消極的 (しょうきょくてき)","definition":"tiêu cực, thụ động","example":"消極的な態度は良くない。","topic":"Mixed N2"},
  {"id":"nf-1436","word":"画一的 (かくいつてき)","definition":"đồng nhất, rập khuôn","example":"画一的な教育を見直す。","topic":"Mixed N2"},
  {"id":"nf-1437","word":"段階的 (だんかいてき)","definition":"theo từng giai đoạn","example":"段階的に進める。","topic":"Mixed N2"},
  {"id":"nf-1438","word":"根本的 (こんぽんてき)","definition":"căn bản, triệt để","example":"根本的な解決が必要だ。","topic":"Mixed N2"},
  {"id":"nf-1439","word":"総合的 (そうごうてき)","definition":"tổng hợp","example":"総合的に判断する。","topic":"Mixed N2"},
  {"id":"nf-1440","word":"飛躍的 (ひやくてき)","definition":"nhảy vọt","example":"技術が飛躍的に発展した。","topic":"Mixed N2"},
  {"id":"nf-1441","word":"致命的 (ちめいてき)","definition":"chí mạng, nghiêm trọng","example":"致命的なミスを犯した。","topic":"Mixed N2"},
  {"id":"nf-1442","word":"献身的 (けんしんてき)","definition":"tận tụy, cống hiến","example":"献身的に患者を看護する。","topic":"Mixed N2"},
  {"id":"nf-1443","word":"楽観的 (らっかんてき)","definition":"lạc quan","example":"彼は楽観的な性格だ。","topic":"Mixed N2"},
  {"id":"nf-1444","word":"悲観的 (ひかんてき)","definition":"bi quan","example":"悲観的に考えすぎないでください。","topic":"Mixed N2"},
  {"id":"nf-1445","word":"建設的 (けんせつてき)","definition":"mang tính xây dựng","example":"建設的な意見を出す。","topic":"Mixed N2"},
  {"id":"nf-1446","word":"破壊的 (はかいてき)","definition":"phá hoại","example":"破壊的なイノベーション。","topic":"Mixed N2"},
  {"id":"nf-1447","word":"典型的 (てんけいてき)","definition":"điển hình","example":"典型的な日本人の考え方。","topic":"Mixed N2"},
  {"id":"nf-1448","word":"象徴的 (しょうちょうてき)","definition":"tượng trưng","example":"富士山は日本の象徴的な山だ。","topic":"Mixed N2"},
  {"id":"nf-1449","word":"衝動的 (しょうどうてき)","definition":"bốc đồng","example":"衝動的な買い物を控える。","topic":"Mixed N2"},
  {"id":"nf-1450","word":"自発的 (じはつてき)","definition":"tự phát, chủ động","example":"自発的に行動する。","topic":"Mixed N2"},
  {"id":"nf-1451","word":"強制的 (きょうせいてき)","definition":"cưỡng chế, bắt buộc","example":"強制的に参加させられた。","topic":"Mixed N2"},
  {"id":"nf-1452","word":"慢性的 (まんせいてき)","definition":"mãn tính","example":"慢性的な人手不足に悩む。","topic":"Mixed N2"},
  {"id":"nf-1453","word":"原始的 (げんしてき)","definition":"nguyên thủy","example":"原始的な生活を体験する。","topic":"Mixed N2"},
  {"id":"nf-1454","word":"革新的 (かくしんてき)","definition":"cách tân, đột phá","example":"革新的なアイデアを生み出す。","topic":"Mixed N2"},
  {"id":"nf-1455","word":"保守的 (ほしゅてき)","definition":"bảo thủ","example":"彼は保守的な考え方だ。","topic":"Mixed N2"},
  {"id":"nf-1456","word":"繊細 (せんさい)","definition":"tinh tế, nhạy cảm","example":"繊細な味わいの料理。","topic":"Mixed N2"},
  {"id":"nf-1457","word":"大胆不敵 (だいたんふてき)","definition":"can đảm, gan dạ","example":"大胆不敵な挑戦をする。","topic":"Mixed N2"},
  {"id":"nf-1458","word":"無難 (ぶなん)","definition":"an toàn, không rủi ro","example":"無難な選択をする。","topic":"Mixed N2"},
  {"id":"nf-1459","word":"見事 (みごと)","definition":"tuyệt vời, xuất sắc","example":"見事な演技に拍手が起きた。","topic":"Mixed N2"},
  {"id":"nf-1460","word":"手際 (てぎわ)","definition":"sự khéo léo, hiệu quả","example":"手際よく料理を作る。","topic":"Mixed N2"},
  {"id":"nf-1461","word":"吟味 (ぎんみ)","definition":"cân nhắc kỹ, lựa chọn","example":"素材を吟味して選ぶ。","topic":"Mixed N2"},
  {"id":"nf-1462","word":"模索 (もさく)","definition":"dò dẫm, tìm kiếm","example":"解決策を模索する。","topic":"Mixed N2"},
  {"id":"nf-1463","word":"葛藤 (かっとう)","definition":"giằng xé, mâu thuẫn","example":"心の中で葛藤している。","topic":"Mixed N2"},
  {"id":"nf-1464","word":"憂う (うれう)","definition":"lo lắng, ưu tư","example":"将来を憂う。","topic":"Mixed N2"},
  {"id":"nf-1465","word":"嘆く (なげく)","definition":"than thở","example":"世の中の不条理を嘆く。","topic":"Mixed N2"},
  {"id":"nf-1466","word":"恨む (うらむ)","definition":"oán hận","example":"彼を恨んでも仕方がない。","topic":"Mixed N2"},
  {"id":"nf-1467","word":"慰める (なぐさめる)","definition":"an ủi","example":"落ち込んでいる友人を慰めた。","topic":"Mixed N2"},
  {"id":"nf-1468","word":"和む (なごむ)","definition":"dịu lại, bình yên","example":"彼女の笑顔で場が和んだ。","topic":"Mixed N2"},
  {"id":"nf-1469","word":"潤す (うるおす)","definition":"làm ẩm, làm thỏa","example":"のどを潤す。","topic":"Mixed N2"},
  {"id":"nf-1470","word":"響く (ひびく)","definition":"vang vọng, ảnh hưởng","example":"彼の言葉が心に響いた。","topic":"Mixed N2"},
  {"id":"nf-1471","word":"輝く (かがやく)","definition":"tỏa sáng","example":"彼女の目が輝いていた。","topic":"Mixed N2"},
  {"id":"nf-1472","word":"映える (はえる)","definition":"nổi bật, đẹp","example":"写真に映える場所。","topic":"Mixed N2"},
  {"id":"nf-1473","word":"際立つ (きわだつ)","definition":"nổi bật","example":"彼の才能が際立っている。","topic":"Mixed N2"},
  {"id":"nf-1474","word":"紛れる (まぎれる)","definition":"lẫn lộn, quên đi","example":"仕事に紛れて悲しみを忘れた。","topic":"Mixed N2"},
  {"id":"nf-1475","word":"染みる (しみる)","definition":"thấm, thấm thía","example":"寒さが身に染みる。","topic":"Mixed N2"},
  {"id":"nf-1476","word":"漲る (みなぎる)","definition":"tràn đầy, dâng trào","example":"やる気が漲っている。","topic":"Mixed N2"},
  {"id":"nf-1477","word":"滲む (にじむ)","definition":"thấm ra, lem","example":"インクが滲んでしまった。","topic":"Mixed N2"},
  {"id":"nf-1478","word":"透ける (すける)","definition":"trong suốt, nhìn xuyên","example":"窓から光が透けている。","topic":"Mixed N2"},
  {"id":"nf-1479","word":"揃う (そろう)","definition":"đầy đủ, tề tựu","example":"メンバーが全員揃った。","topic":"Mixed N2"},
  {"id":"nf-1480","word":"偏る (かたよる)","definition":"thiên lệch","example":"意見が一方に偏っている。","topic":"Mixed N2"},
  {"id":"nf-1481","word":"飽きる (あきる)","definition":"chán","example":"同じ食べ物に飽きた。","topic":"Mixed N2"},
  {"id":"nf-1482","word":"萎える (なえる)","definition":"héo úa, mất tinh thần","example":"やる気が萎えてしまった。","topic":"Mixed N2"},
  {"id":"nf-1483","word":"湧く (わく)","definition":"nảy sinh, trào lên","example":"疑問が湧いてきた。","topic":"Mixed N2"},
  {"id":"nf-1484","word":"募る (つのる)","definition":"tuyển, tăng dần","example":"不安が募る。","topic":"Mixed N2"},
  {"id":"nf-1485","word":"欠かす (かかす)","definition":"thiếu, bỏ lỡ","example":"朝食を欠かさない。","topic":"Mixed N2"},
  {"id":"nf-1486","word":"鍛える (きたえる)","definition":"rèn luyện","example":"体を鍛える。","topic":"Mixed N2"},
  {"id":"nf-1487","word":"蓄える (たくわえる)","definition":"tích trữ","example":"知識を蓄える。","topic":"Mixed N2"},
  {"id":"nf-1488","word":"研ぐ (とぐ)","definition":"mài (dao), vo (gạo)","example":"包丁を研ぐ。","topic":"Mixed N2"},
  {"id":"nf-1489","word":"磨く (みがく)","definition":"đánh bóng, rèn giũa","example":"腕を磨く。","topic":"Mixed N2"},
  {"id":"nf-1490","word":"操る (あやつる)","definition":"điều khiển, thao túng","example":"ロボットを操る技術。","topic":"Mixed N2"},
  {"id":"nf-1491","word":"束ねる (たばねる)","definition":"bó, tập hợp","example":"チームを束ねる。","topic":"Mixed N2"},
  {"id":"nf-1492","word":"束縛 (そくばく)","definition":"ràng buộc","example":"束縛から自由になりたい。","topic":"Mixed N2"},
  {"id":"nf-1493","word":"解雇 (かいこ)","definition":"sa thải","example":"不正行為で解雇された。","topic":"Mixed N2"},
  {"id":"nf-1494","word":"勧告 (かんこく)","definition":"khuyến cáo","example":"是正勧告を受けた。","topic":"Mixed N2"},
  {"id":"nf-1495","word":"苦情 (くじょう)","definition":"khiếu nại, phàn nàn","example":"苦情を申し立てる。","topic":"Mixed N2"},
  {"id":"nf-1496","word":"申告 (しんこく)","definition":"khai báo","example":"確定申告をする。","topic":"Mixed N2"},
  {"id":"nf-1497","word":"届出 (とどけで)","definition":"đăng ký, khai báo","example":"婚姻届を届け出る。","topic":"Mixed N2"},
  {"id":"nf-1498","word":"執行 (しっこう)","definition":"thi hành, chấp hành","example":"法律を執行する。","topic":"Mixed N2"},
  {"id":"nf-1499","word":"制裁 (せいさい)","definition":"trừng phạt, chế tài","example":"経済制裁を科す。","topic":"Mixed N2"},
  {"id":"nf-1500","word":"和解 (わかい)","definition":"hòa giải","example":"長年の争いが和解に至った。","topic":"Mixed N2"},
  {"id":"nf-1501","word":"訴訟 (そしょう)","definition":"kiện tụng","example":"損害賠償の訴訟を起こす。","topic":"Mixed N2"},
  {"id":"nf-1502","word":"弁護 (べんご)","definition":"biện hộ","example":"弁護士が被告を弁護する。","topic":"Mixed N2"},
  {"id":"nf-1503","word":"審議 (しんぎ)","definition":"thẩm nghị, xét duyệt","example":"法案を審議する。","topic":"Mixed N2"},
  {"id":"nf-1504","word":"議決 (ぎけつ)","definition":"biểu quyết","example":"予算案が議決された。","topic":"Mixed N2"},
  {"id":"nf-1505","word":"施行 (しこう)","definition":"thi hành (luật)","example":"新法が来月施行される。","topic":"Mixed N2"}
]

print(f"Total cards in batch 3: {len(cards)}")

with open('/home/adminstrator/code/test/language-app/src/data/n2/flashcards-batch3.json', 'w', encoding='utf-8') as f:
    json.dump(cards, f, ensure_ascii=False, indent=2)

print("Done! Created flashcards-batch3.json with 500 cards.")
